---
output: hugodown::md_document
title: "Impatience and disrespect"
type: "post"
summary: "What happened to the nice lady?"
author: "Danielle Navarro"
tags: []
date: 2021-05-21
---

There was a time in my life when I was a reasonable person, with reasonable questions about transgender issues. There were a lot of things I didn't understand about transgender people, their lives, and why they wanted the things they wanted. It was a topic I cared about, but knew very little about. There were no transgender people in my life. It wasn't part of my world, but I wanted to be considerate. So I did what many other reasonable people would do: I asked my reasonable questions online, as politely as I possibly could, in the hope that someone would explain things to me. I meant no harm and intended no offence. Sometimes when I asked these questions, I'd receive a polite answer. Other times, I would be met with extreme anger. Trans people would be *furious* at me, just for asking an innocent question. In all honesty, I thought they were kind of unhinged. Later, when I transitioned, I told myself I wouldn't be that person. I wouldn't lash out angrily at people for no reason. After all, I was a reasonable person, and I knew how hurtful it felt to be yelled at for no obvious reason.

Oh you sweet summer child.

It's not that I wanted to become angry. I didn't turn into a radical. I didn't become an activist. When I've written posts on this blog, I've tried to be careful not to overstate my claims. In real life I have tried to be patient. I've tried to be kind. I really understand that most cisgender people don't have much of a grasp of transgender issues, and I try to be patient. Honest, I really try. And yet I am finding that despite my best effort, I'm slowly turning into that unhinged trans person yelling at strangers on the internet who haven't really done anything wrong. I've snapped at multiple innocent people lately, and okay, sometimes they actually did say something a little wrong or naive, but nothing that justified the level of anger that came out. And okay, yes, whenever I could I've apologised to them and tried to make amends. It doesn't change the fact that I've been inappropriately angry. 

What happened? I've been trying to make sense of this change in my behaviour, and the best explanation I have is exhaustion. I started transitioning almost five years ago now, and to say that it's been a grim five years would be something of an understatement. It's easy to list off individual incidents: I haven't enjoyed being physically assaulted, I haven't enjoyed being threatened, and I can't say I've particularly enjoyed the numerous humiliations that transition has required. Those make nice, pithy stories that cisgender people can relate to, and when I talk about those kinds of incidents everyone understands why I'm not holding up very well. 

But it's not really the big things that have eroded my ability to cope. It's the constant grind of little things. 

It's the happy father's day messages. The emails addressed to Daniel. The women's group that conspicuously doesn't include me. The guy making jokes about men and telling me "you know what it's like haha". The 59th person asking me about surgery. The 721st person asking me what gender identity really is. The requests for help from cisgender colleagues who have just discovered that one of their grad students is transitioning. The dogwhistles on twitter. The trolls on twitter. The awkwardness of outing myself unexpectedly to someone who I thought already knew. The constant sense of shame, this feeling that I am something unnatural. The people who tell me without hesitation that I am delusional. The man who offers "cash bonus to suck your ladycock" as his first words to me on a dating app. The zoom meeting to discuss the perception and cognition curriculum when I'm trying to contain my grief about the latest bathroom bill passing. Not a day goes by without one of these things happening. Each one hurts a little, and I never seem to heal from the last little cut before the next one comes. 

It's even the emails from people telling me that they admire me, that I am a role model. Sometimes it's from another trans person, sometimes it's from a cis person who has a trans person in their life that they care for. Each time I get one I am deeply touched that someone would entrust me with this kind of respect. People early in transition, still not public, and they have chosen to tell *me*? It is an honour I hardly deserve, and yet just this week alone I've had three people come out to me in private. What am I supposed to do with that? Better than anyone else I know how undeserving I am of other people's trust. I can't offer advice or guidance: I'm barely coping myself. Knowing that others see me like this is an honour, but also a source of anxiety. Honestly, I'm a really unreliable person: all I can do is fail them. 

All these little things add up, and require a lot of emotional strength to handle. Strength I don't have. In real life I don't have trans friends of my own I can talk to. I barely have any friends at all, really. I'm doing the bare minimum to make it through my job, trying my best not to be a terrible parent to my kids, and just lately I've developed a really obnoxious smoking habit. I have my good days, but on the whole I'm not doing well. Whatever emotional resilience I might have had to begin with, it's mostly gone. 

Apparently I've also become quite whiny. 

Okay, *more* whiny. Whatever. The point of this isn't really to tell a sad story. As trans lives go, mine is a pretty good one. I have a good job, I have a nice place to live, most of my documentation has been updated and most of the time I pass. That's much better than I'd hoped for when I started transitioning. This isn't a "woe is me" kind of story, it's something else.

It's a story about what happened to my patience, and where all this anger came from. I was once a very patient person. Kind, forgiving, and nice. In some contexts I still am that person. I will never run out of patience for my kids. I will always have time for my students. If you have an R question I will do my best to answer within the time constraints I have. If a friend needs someone to vent to, I'll be there for them. My anger is quite specific: I have lost patience with cisgender people. I'm not here to satisfy your curiosity. I'm not your fetish. I'm not your intellectual toy. 

Above all else, I am not your debate topic. 

If you are a cisgender person who wants to have an academic discussion about the metaphysics of gender, or what rights a person like me should be allowed to have, or anything along these lines, don't expect me to be kindly disposed toward you. I won't be. In fact, I will probably be angry at you before you even start talking. I don't want to be the subject of your fucking dissertation. I don't care about your hypotheticals. I hate that you do this, that you take something that is central to my life, and you make a cute little word game from it. In this situation I am not the person holding power, and I am angry at you. I am *furious*. I feel rage in a way I have never felt before. This anger is not a thing I understood before I transitioned. That version of me, that very "reasonable" person just asking questions, he did not understand it. When trans people would get angry at him, he did not understand why. Years later, as my anger at cisgender people has grown, I understand it better.

If you want to know what happened to my patience, the answer boils down to a simple question of power. Transgender people have little power: we have no authority, no institutional leverage, and the world has not been set up in our favour. We have suffered life long abuse, and these discussions are deeply personal. None of this is a politics game to us, none of it is an abstraction. Historically we have lived at the margins of society, and right now -- in the real world rather than the fevered imaginations of bigots -- there is a massive political fight over our lives that we didn't start. We didn't ask for this. All we want, all we have ever wanted, is to be able to live our lives in peace, with a modicum of safety and dignity. It is not transgender people passing laws targeting cisgender people. It is not transgender people subjecting cisgender people to dehumanising debates about what they are. It is not transgender people trying to force people to live like us. It is you. Cisgender people are doing all those things to us, and you expect us to be *nice* to you as well? To debate you? Do you expect us to greet you with roses? To be calm and reasoned while you hold a knife to our throats? I don't think so. 

It is easy to be calm and patient when you are safe, when you are the one with power. When I teach my classes, parent my children, or help novices with R, I am the one with power. In those situations I am calm, I am patient, and I am nice. When you want to have a cute little philosophical discussion about transgender lives and identities, I am not the one with power. On the contrary, it is you asking me to participate in a debate while holding my human rights hostage. No, I will not be nice to you while your boot is on my neck. I tried that already, in the hope that you'd remove the boot voluntarily. You haven't done that. I will not waste my energy treating you with a respect that you don't accord me.

<br><br>

