baseURL = "https://essays.djnavarro.net"
languageCode = "en-us"
title = "Essays :: Danielle Navarro"
theme = "hugo-rocinante"
paginate = 10
summaryLength = 0
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "Danielle Navarro"

[params]
  mainSections = ["post"]
  email = ""
  favicon = ""
  about = "Miscellaneous personal writings by [Danielle Navarro](https://djnavarro.net). More of a personal journal than anything else. Sometimes I write essays in the sense of short pieces of writing on a specific subjects. At other times, posts are simply essays in the sense of being attempts or tries to do or say something. Often emotional."
#  [[params.links]]
#    [[params.links.link]]
#      name = "Essays"
#      href = "https://essays.djnavarro.net"
#    [[params.links.link]]
#      name = "Twitter"
#      href = "https://twitter.com/djnavarro"
