baseURL = "https://essays.djnavarro.net"
languageCode = "en-us"
title = "Essays :: Danielle Navarro"
theme = "hugo-rocinante"
paginate = 3
summaryLength = 0
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "Danielle Navarro"

[params]
  mainSections = ["post"]
  email = ""
  favicon = ""
  about = ""
#  [[params.links]]
#    [[params.links.link]]
#      name = "Essays"
#      href = "https://essays.djnavarro.net"
#    [[params.links.link]]
#      name = "Twitter"
#      href = "https://twitter.com/djnavarro"
