---
title: Still the same
author: Danielle Navarro
date: '2020-05-27'
slug: still-the-same
type: post
summary: "I am haunted by a terribly pedestrian phrase."
---

I am haunted by a terribly pedestrian phrase. "You're still the same person". It is a phrase offered with kindness, as a reassurance of sorts, usually on those occasions when the subject of my gender transition arises. It's an expression of support. How you appear to the outside world may have changed, my interlocutor concedes, but on the inside you're still the same person I've always known and liked all these years. The unspoken implication hangs in the air: things will remain the same.

They won't though. Everything changes.

Some changes are easier to handle than others. My name was Daniel and now it is Danielle. Daniel wore blue jeans and black t-shirts. Danielle wears blue jeans and black t-shirts too, albeit with nicer boots than he ever owned. Daniel was "he", Danielle is "she". He had a beard, she has breasts. There's an element of cognitive dissonance about the topic, but not that much. It does take time for the weirdness to fade, but fade it most certainly does. The hardest thing to accept, that people deny the hardest, is the fact that I'm not the same person anymore. 

Oh everybody changes all the time, they'll say breezily, as though I'd admitted that I don't like pizza anymore. Again the implication hangs unspoken: at a deep level you are still him and I don't have to change my mental representation of you. Please don't make me meet the new woman. I liked him -- what if I don't like her? What if she doesn't like me? You're still *mostly* the same as him right? To me it feels like they're negotiating, bargaining to see how much of Daniel they can keep.   

The bargaining doesn't really work. Yes, often I would try to accommodate. I can work on Daniel's research projects, I can teach his classes, I can do a lot of things other people needed him to do. But I'm not invested in them the same way he was. Danielle, it turns out, has her own ideas about what matters in life, and first passage time density computations for Weiner diffusion processes are not numbered among them. And so eventually the time comes when I can't be the person they want. Daniel was not an indolent man, and as competent as Danielle is, she's not so good at what she does that she can do his job as well as her own. My boundaries are different to his. When I start to assert them it comes as a shock, and people I care about get incredibly angry at me. 

It surprised me, but maybe it shouldn't. Every time I do things that he would not have done -- or worse, don't do something he would have -- it seems to force people to realise the thing that has been staring them in the face the whole time. Daniel is gone and he's been gone a long time. I didn't even grasp it myself initially. For the first couple of years as Danielle I tried to hold onto many things I used to care about. It was my way of clinging to the man whose life I've inherited, as though his memories could ward off the misery over what -- who -- I'd lost. I ought not be surprised that other people do the same. 

It is, I have come to realise, a kind of grief.

People who have only ever known me as Danielle don't go through this. To them, "Daniel" is an abstract concept. Of course he must have existed. How else could Danielle be the person she is now, if not for him? But that's just an abstraction. They didn't really know him. At an emotional level, I have always been Danielle to them. There is no sense of loss. My transition never caused them to lose someone they liked, someone they loved.

I wish I could say this story has a happy ending, but I don't know if it does. In transition I've lost a lot of friends, often very dear ones, not through prejudice or intolerance, but through grief. His friends sometimes find me discomforting; I feel the same about them. We fall back on old habits, and for a moment or two it is just like old times. 

It makes it harder to accept our shared loss.
