---
output: hugodown::md_document
title: Daniel
author: Danielle Navarro
date: '2020-12-26'
slug: daniel
summary: "Slivers of memory"
type: post
---

Sometimes I see a dead man's reflection in the mirror. A little flash of memory of his face, so similar to my own. Not the same though. My skin has a different texture, softer and smoother. My facial expressions are not his. His perpetual stubble is a distant memory, but one I have not forgotten. 

I have nightmares about that reflection sometimes. Body horror dreams in which his face returns, my body transformed back into his. My breasts dissolving, hair regrowing from my arms, my back, my chest, the dark shadow returning to my face. His musculature twisting my birdlike arms into grotesque knots, his testosterone set loose inside me, like poison.

He wasn't a monster. Or, at least, I don't think he was. I don't think I ever knew him well enough to be sure. I know he tried to be a good man, even if he was never very competent as one. His memories are painful for me to recall. He'd been hurt rather badly, I think, and more than once. Sometimes you don't heal from your injuries. He wanted so desperately to be gone, to erase himself, and in a way I suppose he succeeded: there isn't much left of him anymore. 

I wonder what he would think of me sometimes. Would he pity me? Would he feel proud of me? Would he even like me? In the brief time I've been here I've done things with his body that he would have found unimaginable, taken risks with his life that he would have found shocking. I have burned his bridges, traded his home for magic beans, poisoned his wells, and salted the earth in his garden. Perhaps he would despise me. Perhaps I would be a disappointment to him. I suppose I'm unlikely to ever know. All I know is that his life shattered when he left and I tried my best to pick up the pieces.

I do not want him back.

