---
title: I am what I am
author: Danielle Navarro
date: '2020-08-12'
slug: i-am-what-i-am
summary: "Mentally ill."
type: post
---

Mentally ill. I spent many years trying to avoid the label, or at least refusing to accept that the label applied to me. It's not a pleasant idea to acknowledge that something is wrong with your own mind, that something about how you think or feel is badly broken. That your perception of yourself and of the world might be deeply, fundamentally wrong. The thought is terrifying. If you cannot rely on your perception or your reason, then how can you possibly be trusted to exercise your own autonomy? What basis is there to claim that you should be allowed freedom to control your own life? Nobody in their right mind would want to be mentally ill.

<p align="center">: :::</p>

In the 42 years I've been alive, I've been forced to acknowledge mental illness in myself more than once. The first time I was seriously confronted with it occurred when I was 16. I was severely depressed, and had started cutting my wrists. It wasn't a suicide attempt, just regular self-harm. I don't think I was doing it for attention: I managed to keep it secret for several months, which doesn't seem like the kind of thing you'd do if you wanted attention. I think I just wanted to hurt myself really, and I'm not sure there was anything more to it than that. But I did get caught eventually, and when it happened I was forced to acknowledge that I was depressed.

The second time occurred when I was 25, I think? In the years that had passed, my depression had returned many times and never quite vanished. It would come and go, but not in any predictable way that I could see. I wasn't depressed because something bad had happened (though of course there were times when bad things did happen, just like they do to everyone else), I was simply depressed. The depression wasn't correlated with the events in my life, so it seemed implausible to believe in the "depressive realism" hypothesis (in my case): whatever the problem was, it was coming from within me.

The third time, I was 33. I had a young child, my mother was dying of cancer, and everything in my life seemed to be falling apart (because, well, everything kind of sucked at the time). I didn't find it easy to make sense of my own emotions about all those things, but eventually I did: I was anxious. Hardly an unusual emotion under those circumstances, but there was a lot of it. It started to dawn on me that the anxiety and depression (though obviously related) are distinct things. I've never really had a good label to attach to the anxiety: at different times I've been diagnosed with generalised anxiety, panic disorder, and probably a lot of other things too. It's even been suggested that I have post-traumatic stress disorder (it's a long story). I'm not particularly interested in the labels anymore: I seem to accrue a new one every time on a semi-regular basis, and I'm not sure any of them have provided me with any deep insight.

Regardless of what we decide to call them, these mental illnesses are not fun to live with. However, it's not impossible. Yes, some days I wake in fright for no reason. Yes, I have panic attacks. Yes, some days I wake up longing for death, so miserable that I can barely drag my lazy arse out of bed. This is a rubbish way to live, quite frankly, and it doesn't exactly endear me to the people in my life who have to deal with it. Quite apart from everything else it's *embarrassing*: I have meltdowns from time to time and sometimes they happen in public, and no-one needs that shit.

Nevertheless, these conditions are manageable. Between medication, therapy, exercise and -- okay I confess I'm terrible at this one -- a decent diet it's possible to keep the worst of it under control, and for the most part I manage to function pretty well. Depression and anxiety are mental illnesses that I have learned to live with. They are awful, but in and of themselves they do not lead to the kind of melodramatic terror I described in the first paragraph to the essay.

Gender dysphoria is a different story.

<p align="center">:: ::</p>

I'm not exactly sure when I started transitioning. To me it seems that gender transition begins when you start taking public action. It's one thing to admit to yourself that you are transgender, quite another to actually do something about it: deliberately, of your own volition, and with the intent to make a permanent change. To my way of thinking, transitioning is the second part. Even with that distinction in mind, it's pretty hard to pick a moment. I could date it all the way back to some of my gender nonconforming attire back in 2002 but that seems a vacuous claim to me. A slightly more plausible answer might be 2013 when I started trying out gender nonconformity in more of a deliberate fashion from time to time, but it wasn't public. The first thing I can think of that meets the criteria I listed above would be when I started deliberately feminising my appearance at work, in full knowledge of why I was doing it. The internet being what it is, I can track down the date it started: early in August 2016. So it's been four years now.

<p align="center">::: :</p>

The thing that I find most disorienting about gender dysphoria is that I don't quite know how to describe it. Without wanting to make any claims about what other people feel -- because obviously I have no idea what it feels like to them -- I don't find any of the euphemisms very compelling. 

I don't feel like I was "born in the wrong body": quite clearly this is my body and while I hate the fucking thing I can't really think of what it would mean to be born in the wrong one. That phrase doesn't mean anything to me. 

Along the same lines I don't "feel like a woman" either. That makes even less sense to me. I feel like ... me? That's kind of all there is to it. At best I might say there's a sense in which it feels like I "should have" been born a woman, that I'd have been a lot fucking happier from the beginning if I had a body like that rather than one like this. That kind of makes sense to me, though it's a bit peculiar because any reasonable interpretation of the way the world works suggests that women get the short end of the stick. Regardless, it doesn't seem to make sense to me to claim that "I feel like a woman". That just sounds like a Shania Twain song.

At the same time, I don't feel like I'm engaging in a "gender performance" either. Actually, I kind of find that one insulting. I found an old quote from [Julia Serano](https://jezebel.com/gender-is-not-just-a-performance-5647120) that captures my feelings on that particular topic nicely: 

> If one more person tells me that "all gender is performance," I think I am going to strangle them.

Oh my yes. I loathe the phrase. As Serano says:

> Sure, I can perform gender: I can curtsy, or throw like a girl, or bat my eyelashes. But performance doesn't explain why certain behaviors and ways of being come to me more naturally than others. It offers no insight into the countless restless nights I spent as a pre-teen wrestling with the inexplicable feeling that I should be female. It doesn't capture the very real physical and emotional changes that I experienced when I hormonally transitioned from testosterone to estrogen. Performance doesn't even begin to address the fact that, during my transition, I acted the same, wore the same T-shirts, jeans, and sneakers that I always had, yet once other people started reading me as female, they began treating me very differently. When we talk about my gender as though it were a performance, we let the audience — with all their expectations, prejudices, and presumptions — completely off the hook.

Besides, it's dangerous to think this way:

> Look, I know that many contemporary queer folks and feminists embrace mantras like "all gender is performance," "all gender is drag," and "gender is just a construct." They seem empowered by the way these sayings give the impression that gender is merely a fiction. A facade. A figment of our imaginations, endlessly mutable and malleable. And of course, this is a convenient strategy, provided that you're not a trans woman who lacks the means to change her legal sex to female, and who thus runs the very real risk of being locked up in an all-male jail cell. Provided that you're not a trans man who has to navigate the discrepancy between his male identity and female history during job interviews and first dates. 

Whenever someone says "gender is performance" all I can think is that you're not taking this shit seriously.

The best (or perhaps "least bad") way to describe it that I can come up with is that for a long time I have had a sense of distress associated with my sexed body. What I mean by this is that I hated having a penis and I hated everything that happened to my body during puberty. The whole thing felt like body horror, and no, I didn't know why I felt that way. What I did notice, eventually, is that my body felt less gross to me in situations where I was able to appear feminine. That when I started transitioning, I felt a sense of "familiarity" with my own reflection that hadn't been there before? Or maybe just this low-grade sense of disgust I used to have had disappeared? Something like that anyway. The point is that every time I took a step in the direction of transitioning, of changing my body, my behaviour and my attire, I felt a sense of relief and comfort. Any time I considered going back, I felt dread and disgust. As far as I can tell, it was those emotional responses that drove my transition.

I don't *think* that counts as a delusion, does it? 

It's weird, certainly. I'll concede that it's a strange situation to find yourself in. Equally, I'm obviously not exactly in the majority for feeling like this: there's clearly something about me that isn't the same as most people. But as far as I can tell there's nothing in what I've written here that suggests I have lost the faculty of reason or cannot trust my perception of the world?

<p align="center">:::: :</p>

Some things I have seen written about me by other people on twitter in the last couple of days.

> you are definitely a guy ... you are a guy who for whatever reason thinks he's a girl ... it has to do with reality ... people are encouraging you ... people are telling you what you want to hear, not what you need to hear ... its REALITY ... if you can't grow out of those sorts of things, you'll never be an adult ... back in the day those people would be in mental care facilities

In my experience, there aren't many people who are willing to say these things directly to my face, even on twitter. Most people are actually quite nice to me. Of course, there are a lot of people who say exactly this kind of thing (and more) elsewhere, on twitter and on other websites. When they aren't talking directly to me, there are a lot of extraordinarily horrible things I see people saying about people like me. But thankfully, no-one will tell me things like that to my face.

I mentioned I have anxiety though, right? The obnoxious things that people do sometimes say to me are so eerily similar to my worst fears, and so similar to the unpleasant things I see people saying in other places, that I start wondering. Maybe those comments are right: 
> you are definitely a guy ... you are a guy who for whatever reason thinks he's a girl ... it has to do with reality ... people are encouraging you ... people are telling you what you want to hear, not what you need to hear ... its REALITY ... if you can't grow out of those sorts of things, you'll never be an adult ... back in the day those people would be in mental care facilities

This time around it's not *them* saying it, it's me. It's trivially easy to deal with one minor troll on twitter saying nasty things; it's a lot harder when it's not a twitter troll but all your personal demons telling you the same story. All those fears I mentioned at the beginning of the essay now come into play:

Perhaps my perception of myself and the world is irredeemably flawed. Perhaps everything I wrote above about how my transition unfolded is a comforting lie I have told myself. Maybe I should be in a mental care facility: can I really be trusted to exercise my own autonomy? 

Maybe I truly am delusional.

<p align="center">::::: :</p>

On twitter I wrote this thread:

> My fear stems from having grown up in a world where it was accepted as "obvious truth" that people like me are inherently disordered & the simple fact of being transgender was prima facie evidence of delusion. We could *never* be trusted to be rational
>
> This world view has changed, but only recently. Even 10 years ago (when I was 32) it was still widely accepted that being transgender *is* a mental illness. That world view is still very common, and it is still in my head just as much as everyone else of my generation
>
> When a random troll appears on twitter to make some silly and childish remark about trans people being mentally ill, it has a bigger effect on me than you might think. It reasserts that belief I was raised with. It makes me question myself. Maybe I *am* delusional, I think.
>
>  When I see my academic colleagues posting videos mocking trans women's gender identity [I linked to someone doing this] it has a larger effect than simply "hurting my feelings". It makes me question my sanity
>
> Because I am trans, these things are sent to me by friends, colleagues, etc and I necessarily get dragged into things I'd prefer not to. For example, I've just spent 3 weeks arguing patiently with a colleague that some of the things he's written about us are unkind
>
> Not by choice then, my everyday environment is one in which I am constantly exposed to material that mocks me, humiliated me, & (often quite deliberately) asserts that I am delusional; and every day I remember what the world used to be like and the world view I was raised with
>
> This adds up to something like a version of the Solomon Asch experiments: I see a world in which my very sanity is considered a debatable subject. But because everyone around me doesn't get exposure to that environment, they don't notice how bad it is
>
> So what happens is this cycle. I see something that causes distress and I try to ask for help (sometimes on Twitter). Other people don't see any of the surrounding history or context and they shrug it off and say "just ignore it - they're just trolls"
>
> This throws me for a loop. From my perspective I am struggling to force myself to believe that I am sane, that I am not delusional simply because I am transgender. And I have asked for help, and everyone seems... indifferent to the level of terror I feel.
>
>  So what should I make of all this? Is it me (one person) misperceiving the world is is it you (many, many people). Ockham's razor suggests it is me. That I am wrong, that I am unable to correctly perceive the state of the world... that I am delusional.
>
>  From that point it spirals. I have no reference point to determine whether my own reason is trustworthy and every signal I am getting from my friends, my family, my peers suggests that I am in fact, delusional.
>
>  What I'm getting at here is that there is this mechanism by with other people's silence (which to me is quite conspicuous) reinforces my fear that I am mentally ill. So... here I am, begging people to do a better job of being explicit. Otherwise I can't escape the loop
>
> TL;DR: If you genuinely believe that I am not delusional, and you don't want to contribute to the spiral that makes me believe that I am, I need people to be willing to say those words out loud - because I have no reason to think my sanity is "obvious".

