---
title: White Tears/Brown Scars
author: Danielle Navarro
date: '2020-06-27'
slug: white-tears-brown-scars
summary: "Notes on \"White Tears, Brown Scars\" by Ruby Hamad"
type: post
---

Ruby Hamad (2019). *White Tears/Brown Scars*. Melbourne University Press.

The book opens with a chapter describing the fallout from her article in The Guardian on how white women use strategic tears to silence women of colour. The running theme in the chapter is that white women occupy a strange place in a society that is racist and patriarchal at the same time. On the one hand white women are positioned as subordinate to white men, required to play the role that white men require, leading to no end of violence. Misogyny is pervasive and white women's opportunities are severely restricted. On the other hand we have this norm that "white womanhood" is something special that needs to be protected and cherished. That's not hard to verify if you look at modern racist writing. Take for example the two versions of the [fourteen words](https://en.wikipedia.org/wiki/Fourteen_Words) slogans used by white supremacists: *"We must secure the existence of our people and a future for white children"* and *"Because the beauty of the White Aryan woman must not perish from the earth."* In these slogans the purity of white women -- and white children, which of course evokes notions about white women as dutiful mothers, women as givers etc -- are used as the justification for overtly racist ideologies. What Hamad notes is that this "privileged, sympathetic victim" status allows white women to use tears as a weapon against women of colour.^[This, I note in passing, rings true to me as a trans woman. Anti-trans narratives follow the same script. Trans women are portrayed as male predators, threats to cisgender women who invade the to-be-protected spaces that properly belong to (white) cisgender women and thus provoke aggression from men. In contrast, trans men are portrayed as female victims, coerced into transitioning. Anti-trans activists have no interest in protecting their feminine sons (who may in fact be transgender daughters) from "the transgender menace" but they do get very protective of their "daughters" (or transgender sons). And so on.] Hamad describes the experience of encountering it (on p12-13) like so:

> women of colour who attempt to address an issue that is detrimental to them in some way almost invariably come up against a wall of white fragility so immovable, so lacking in empathy, so utterly unrepentant, that the first few times it happens, you naturally assume you are imagining it, that you are the problem, that you should have gone about things differently and you will go about things differently from now on. So you do. You adjust your reactions, you try to play nice, you watch your tone. But it keeps happening---angry, sad, yelling, begging, it doesn't seem to matter---until at some point you, as a woman of colour realise in shock that regardless of the facts of the situation the real problem isn't even about you. It is how white society regards you. It is how white society treats you. Because you, as a woman of colour, do not measure up to their image of what a woman is and should be in order to be believed, supported and defended."

In case the point is lost on the reader, she continues:

> Many white women reading this will know exactly what I am talking about, becasue this very thing happens between men and women the condescending dismissals, the exaggeratedly mystified claims of unprovoked hysteria and unhinged emotion the gaslighting. What I and many women of colour before me, and no doubt after me, are asking is that white women open their minds and hearts when women of colour talk about the double whammy we are dealt. That even as we agitate against the sexism of a male-dominated society, because it is also a white-dominated society we are also assailed with racism, and often this comes from white women who turn their sanctioned victim status on us.

---

In chapter 2, Hamad talks about how women of colour are sexualised, portrayed as promiscuous, and fetishised by white society. The chapter takes a cross-cultural perspective -- her discussion covers Black women in the US during slavery, Aboriginal women in colonial Australia, stereotypes about Arab women or "Oriental" women, Native American women, and more -- and it is hard not to notice that the pattern is eerily similar across contexts. Hamad writes (p 26): 

> the labelling of black women as 'easy' served a double purpose: as well as absolving white men of any shame or wrongdoing by positioning black women as less evolved, animalistic and ruled by their own carnal desires, it differentiated black women from white women, thereby justifying the sexualisation of the former and the sexual repression of the latter

This discussion continues in chapter 3 where she talks about how the sexualisation of women of colour intersects with tropes about the Angry Black Woman and her cousin the Angry Brown Woman. On p50:

> appearance is used to reduce millions of women of the various races and ethnicities that populate the twenty-one countries of Latin America into one hot-blooded, objectified sex symbol. Not only does this erase the racial complexity of the region, it leaves real-life Latinas anxious about their looks and their behaviour as they struggle to either confound or conform to the archetype. 'Men I have gone on dates with have expected me to display maximum cleavage from the start, expressed concerns over ever getting into an argument with me for fear of my "passion" coming out, and complimented my curves at every turn,' writes Irina Gonzales on the website Hip Latina. 'It felt as if my anger and passion were taken as a joke because it's simply an expected part of my personality'

The chapter goes on to argue that white society used (and uses) norms about sex and gender as a tool to maintain racial hierarchies as well. The core of the claim, as I understand it, is captured in this quote on p56:

> evolitionary race scientists effectively split the civilised, aka white, body in two. To the male half went the higher intellectual faculties of reason, logic and objectivity, and to the female went excessive sentimental responses and the accompanying tendency to irrationality and impulsivity

Hamad then gives the example of [Lord Cromer](https://en.wikipedia.org/wiki/Evelyn_Baring,_1st_Earl_of_Cromer) who "oversaw the occupation of Egypt and who was a scathing critic of the status of Arab women ... had ambitions to restructure Egyptian society and politics along European lines ... [and] was a vociferous opponent of suffrage for white women. Indeed, not only was he a founding member of the British Men's League for Opposing Women's Suffrage, he served as president" (p56-57). By implication, part and parcel of maintaining colonial control over an Arab nation was attempting to ensure that the local population maintained precisely the same gendered division that European nations did. As Hamad (p57) puts it, "[t]his is why Cromer both claimed to want to 'free' Arab women *and* denied them education. To him, a free woman was nonetheless subordinate to a man, but she was subordinate in the right---white---way".

Later in the chapter she gives another example that highlights the difficulties faced in contemporary (Australian?) society, attributed to Palestinian-Australian author Amal Awad. On p61:

> Awad recalled to me how the attitude of one male boss in her old newsroom workplace changed towards her once she stopped wearing the hijab: he becme far harsher in his criticisms of her work and more inappropriate in his verbal interactions, such that during one disagreement he told her to 'Get fucked' before smirking, 'Oh that's right, you *can't*'. 


---

Chapter 4 discusses the "(white) damsel in distress" trope, how it is used as a way to render white women subordinate to white men *and* as a way to allow white women to exert control over people of colour, men and women alike. The chapter opens with an example of a wealthy white woman in Southern Rhodesia in the early 20th century who falsely accused her black male lover of rape in order to protect her reputation as an appropriately chaste aristocratic woman, which was a crime punishable by death (though only when it was a white woman raped by a black man, of course---no such harshness was imposed on white men). Hamad discusses how this phenomenon plays out across various historical contexts. She provides a good summary of it (in the antebellum South in the US) on p71:

> During this antebellum period, racial boundaries in the southern states were strictly police and higher-class white women were (theoretically at least) not permitted to travel without an older male chaperone. The burden of representing the inherent superiority of white civilisation fell not on the shoulders of white women, but firmly between their legs. As long as upper-class white women performed their ordained role as the 'angel of the house', were impeccably chaste, and were vulnerable to the mythologised sexual whims of the uncivilised black population, then they had to be defended, protected and shielded from view

A few pages later Hamad highlights how this norm---though placing white women in an incredibly vulnerable position with respect to white men---also provides them with extraordinary power over people of colour, by recounting the depressing story of [Emmett Till's](https://en.wikipedia.org/wiki/Emmett_Till) murder:

> The fourteen-year-old from Chicago was visiting family in 1955 Mississippi when he was accused of whistling at a white woman, Carolyn Bryant, in a convenience store. He was abducted by a group of white men who included Bryant's husband, beaten to death and dumped in the Tallahassee River. His killers were acquitted by an all-white jury. In 2018 Bryant recanted her testimony and admitted that Till had neither whistled at nor harassed her in any way. This is the power of the white damsel in distress.

Suffice it to say, this power is restricted to respectable white women. Women of colour do not receive any such authority, nor do "disrespectable" white women (sex workers and trans women^[Any time I read a book written by a cisgender feminist I have a habit of checking to see whether or not we are mentioned at all, even in passing. Many books fail this trivial test: Hamad passes. She makes an oblique allusion to the difficulties faced by trans women on p83 and an explicit reference on p158 to racism (though not transmisogyny) experienced by a black trans woman. The existence of trans women is also noted explicitly on p138.] are, for example, unable to leverage this power even if they are white). Moreover, this power does not work even for respectable white women if the offender is a white man, as Christine Blasey Ford could no doubt attest. The examples of this phenomenon that run through chapter 4 are depressingly long and familiar.

Chapter 5 is entitled "when tears become weapons" and extends this discussion, focusing more specifically on how white women's tears can be (and are) used as strategic weapons to ensure that women of colour "stay in their place" as it were. Hamad takes some care to point out that this strategy is not always (perhaps rarely?) deliberate, but also makes the strong case that it intent is irrelevant: what matters is not whether white women *intend* to leverage this power against women of colour, but rather the *effect* that this has on those targeted. For me, the key passage in this chapter is on p104:

> Strategic White Womanhood makes personal what is political. It reframes legitimate critiques as petty gripes. It takes the onus off the structures and systems that hold back women of colour and places it firmly on the behaviour or perceived behaviour of the women of colour.

This quote continues with a personal note from Hamad:

> It took me many years to understand what was happening in the interactions and conflicts I'd had with white women over the years. I couldn't understand how and why I would end up apologising to them when I knew they had wronged me and done me harm. I couldn't grasp what would make someone I considered a friend lose her temper with me in a split second and with a contempt so sudden and vicious it left me breathless, and tell me I was being 'mean' to her because I'd simply said that as a white woman she could not know what racism feels like.

Hamad's account rings true to me in two senses. First I recognise myself a little in the white woman. Though I try not to get defensive about race, I've caught myself getting disproportionately annoyed when it is pointed out to me that I am the beneficiary of all kinds of social advantages by virtue of my race. Secondly, and somewhat conversely, were I to write a paragraph about my own nervousness and confusion regarding cisgender women and transmisogyny, it might resemble this one in some respects. 

Chapter 6 follows this further still and argues that the pattern is systematic. When discussing the manner in which white women very often vote for political candidates who are both misogynistic and racist, Hamad argues (p117) that

> These women are not 'gender traitors' choosing their whiteness over their womanhood, as we had thought. Rather, they are *performing* their [white] womanhood ... they take one for the team so that 'our anger at white women conveniently spares the white male voter' [quoting Kyle Schuller] who supported Trump and Moore in even larger numbers.

Toward the end of the chapter (p138) Hamad issues this call to action for white women: 

> White women are not like other women not because their biology makes them so, but because white supremacy has decided they are not. White women must cast aside white supremacy in all its covert as well as explicit forms, and regain the humanity they lost the moment they started to accept the fallacy that their 'race' makes them better than the rest of us. Only then can feminism as a truly global project aimed at bettering the lives of all women emerge

Perhaps it is unfortunate then that this does not seem to be happening. On the contrary (p159)

> we still see whitewashed fiasco after whitewashed fiasco, with women's leadership conferences, feminist magazines and panels offering white women up as the future. It's become a repetitive script: we point out oversights and exclusions and white feminists promise to 'do better', then they promptly make the same mistakes over again. And still, women of colour are expected to remain polite, supportive and even deferential lest we mark ourselves as 'angry' rather than 'assimilated' and find ourselves squeezed out of feminism altogether.

Regarding progressives and left wing politics in general (p161-162)

> The right sees us as threats and their scorn is relentless unless we assimilate, disavow our own cultural heritage and pledge allegiance to whiteness and 'Western civilisation'. The left will claim to be our 'allies', but only as long as we implicitly accept an inferior position and never attempt to get ahead of ourselves, let alone ahead of them. As long as we play the part of their pets. And that means allowing our hair to be stroked or playing the passive silent victim or acting the role of the non-threatening sassy sidekick.

I am bitterly reminded of the white cisgender women who have "joked" to me (at the time a non-passing trans woman) about their desire to physically assault non-passing trans women in bathrooms, who have interrogated me at length about my genitals, who have insistently demanded that I show them my breasts to satisfy their curiosity. And so it is that every time the subject of white feminism comes up, despite being a white woman myself I see nothing to defend in white feminism whatsoever. Nevertheless I too must be polite and deferential lest I be cast out of womanhood entirely. But I digress.

In chapter 8, Hamad discusses the infamous (to Australian readers) [incident](https://www.youtube.com/watch?v=vIskS-7TwVk) in which Kerri-Anne Keneally gave an angry speech on television denouncing the 2019 Invasion Day rallies, and reproducing numerous vicious stereotypes about Aboriginal Australians. The other white people on the panel remained silent, so it fell to the lone person of colour Yuki Stynes to calmly say "Kerri ... you're sounding quite racist now". The nationwide backlash against *Stynes* for pointing this out was staggeringly abusive, and of course drowned out any meaningful discussion of the plight of Aboriginal people. Instead, the cultural discussion revolved around Keneally's hurt feelings. As Hamad notes, this is predictable. It is (to use Toni Morrison's words) part of the "distraction" function of racism. It is nigh impossible to make any progress on Aboriginal rights and sovereignty when it is so easy for one white woman to divert the entire narrative like this. Hamad writes (p 178):

> In white societies, people of colour are used as a wedge. Immigrants are given promises of acceptance and assimilation, such as the citizenship ceremonies pointedly held on Australia Day that encourage us to identify with the nation-state rather than the First Nations. These come with implicit threats of ostracism if we don't comply. Yet, at the same time, we remain excluded from the inner circle. Stynes may have appeared to have penetrated the inner circle, but it was a tokenistic inclusion that could be revoked at any time if she dared to step out of her box. Well, she did step out of her box and her inclusion was revoked.
>
> Through no fault of her own, Stynes' appearance not only was exploited to shift the frame of the debate in favour of whiteness, but also reaffirmed in the minds of white Australians that brown people, particularly (angry) brown women, will never really be one of them. 

One last quote (p210-211):

> Throughout *White Tears/Brown Scars*, I have used words that suggest women of colour are being abused both consciously and unconsciously by white women. I hold to this. Women of colour are in an abusive relationship with whiteness more broadly but especially with white women, who pivot between professing sisterhood and solidarity with us based on gender identification, and silencing and oppressing is by weaponising their White Womanhood ... they will support women of colour only so long as we do not threaten their position above us on that false hierarchy of their own making
>
> This is abuse.



