---
title: Eighty-three, sooner or later
author: Danielle Navarro
date: '2019-09-30'
slug: eighty-three-sooner-or-later
---

<p align="center">[rape, alcoholism, self harm]</p>

<p align="center">~</p>

*My hotel room in Johannesburg is hidden behind an electric fence and three electronically locked doors. The windows are barred and the lights are out. I'm only half sure how I got here. There was a flight, a train, and a winding drive through the dimly lit back streets. I've barely slept in days. I came in from Sydney, there was an interview in Melbourne before that, an open science workshop in Denmark before that. Somewhere in the middle was an introductory programming class, and I'll need to assist in a Tidy Tools workshop when I return. I've forgotten what I'm even doing in Johannesburg. It's a data visualisation workshop, I think, and a keynote for... something. I've lost track though. I'm so tired, I don't understand what is happening and I have only the vaguest sense of where I am, except that I'm curled up in the darkness in the hotel bathroom, wrapped in a blanket, panicking and sobbing uncontrollably as intrusive, graphic thoughts of suicide and self mutilation wash over me, eroding the last reserves of self control I have. I wonder if this is what burnout feels like, I think to myself.*

<p align="center">~</p>

I don't quite know where this story begins. I've struggled with depression and anxiety for as long as I can remember, so much so that they feel like an inalienable part of who I am. I started drinking heavily at age 12, or maybe 13. I can't even remember why I started, and I often wonder how much my parents knew in the beginning. They probably worked out most of it by the time I was 15, when I had my first blackout, and was delivered unconscious to their doorstep. I do know that by that age I'd already fallen into the pattern of drinking to dull the anxiety, to hide my fear, and to mask the discomfort with what was happening to my body.

The cutting started later. I was 16, and in my first year of university, one of those "smart" kids who had been skipped ahead, and I didn't handle it well. I'd started cutting myself almost the moment I'd started university, not for any interesting reason I suppose. In part, it was a cry for help. In part, it way to transform psychological pain into physical pain. The usual story, I guess. I can't claim I was particularly special in this respect. I wasn't very good at hiding it -- not sure I tried very hard -- and later that year I got caught. The university adminstrators threatened to expel me from the residential college where I was living unless I went to see a psychologist, who I dutifully lied to for about six months until everyone forgot about me. 

The unfortunate part is that when I did get caught it was the night of a college formal, and the administrator forced me to put on a suit and dance with the other students where they could keep an eye on me. I was assigned a chaperone, a minder to make sure I didn't hurt myself again. It felt humiliating. I sometimes wonder if anyone else in the room knew what was happening. It felt to *me* like everyone knew, but I've since discovered that people are pretty oblivious.

It's probably no coincidence that all this started with puberty, and got worse over time when all this sex business started. I struggled a long time to make sense of my sexuality. I never had any formal sex education classes -- they were mandatory, but somehow with me skipping different years in different subjects it just got dropped for me -- and I'd always been too embarrassed to talk to anyone about sex. Not that I imagine it would have helped. From what I'm told sex ed classes were pretty useless then. 

Nothing made any sense to me. At times I'd be attracted to men, at other times I'd be attracted to women. I wondered if I was gay, but no-one I knew was out as gay and the stigma was pretty strong, and anyway I was too afraid of men to think much of the possibility. Gay men would sometimes hit on me at bars, and it was distressing to me, but not because I found them unattractive. In retrospect, my unease wasn't at all mysterious: my distress had more to do with the fact that I had never *consented* to men feeling up my ass at the pool table. But it never occurred to me that my consent was actually important. I'd somehow learned all the right lessons about how men have to respect women's consent, but no-one told me that *I* also had the right to say no. I guess I assumed I'd somehow sent them the wrong signal or something, and after a while I just stopped going to those kind of bars.

I didn't really become sexually active until my early twenties. It didn't start out so bad, actually. My first girlfriend was gentle and kind, thankfully. I didn't get raped until my mid-twenties, shortly after the break up. I didn't think of it as rape at the time, though. Who would believe that the cute white lady is a rapist? I couldn't believe it, and I couldn't find any words that described the feeling of violation and disgust I felt towards myself. It couldn't be rape. It must have been the outfit I was wearing, or something I said that led her on. I *must* have consented to it, surely, or else I wouldn't have frozen, wouldn't have let her do that to me. If it *had* been rape, surely someone would have called it that. But no-one did. I did try to tell people what happened, sort of, but I guess the words came out wrong. The boys congratulated me on my rape and all the girls rolled their eyes at me.

It took me years to understand why I have an uncontrollable, visceral disgust for anyone who speaks with the same accent as her.

<p align="center">~</p>


*Johannesburg is kind of a blur. I didn't show up for my workshop. I didn't give my keynote. My hosts were lovely, they filled in for me as seamlessly as they could, I tried to at least be a good guest and show up to the event. Everyone knew that my "illness" was a polite fiction, I think, but sometimes the lie agreed upon serves an important purpose. I leave Johannesburg grateful to the people I'd disappointed and arrive home in Sydney ashamed of how completely I'd fallen apart, yet entirely unable to explain how or why it happened. But life is going on as usual here. I have to finish teaching my classes. I have to TA for this Tidy Tools workshop. I have to keep going. That's that's the job, and just like the UNSW motto used to say, "Never Stop Moving". I can't stop. It's not just work, of course. I have to spend more time with the kids. I have to give my partner a break because I've been travelling too much and this isn't all about me. Just keep moving. I'll be okay.* 

*I barely last two weeks.*

<p align="center">~</p>


The counterintuitive thing about the rape flashbacks is that they didn't start immediately. At first, I studiously avoided thinking about what happened. I most definitely did not think of *her*, ever, not if I could find any way to avoid the thought. If asked I'd say it was just a casual thing. Every now and then I'd have these uncomfortable recollections, immediately pushed aside with an inexplicable sense of ... shame? It didn't make sense. I didn't know why I felt ashamed of it. My friends kept telling me I'd done so well to "score" without even trying, apparently. Better not to think about the subject, I thought to myself. I puzzled over why I couldn't make myself speak her name, not even to myself.

Years later, I understood. I was reading an online discussion about rape, and women were talking about their own experiences in a way I'd never heard. These were topics never discussed in real life, and especially not with someone like me, someone more likely to be perceived as a perpetrator than a victim of sexual assault. It was the first time I'd read a first person account of the freeze response -- of finding yourself unable to move, speak or resist in any way, confused and bewildered by why you're not doing anything to stop this -- and I felt physically ill. It was about that time that the flashbacks started.

<p align="center">~</p>

*The first day at work after Tidy Tools, I have a meeting with a Ph.D. student. I've fallen further and further behind in my supervisory role, and when he suggests the possibility of switching advisors, not only do I enthusiastically agree to it I realise that I have a much bigger problem. I email some colleagues to warn them of what is coming, tell my department head what is going on, and walk straight to the doctor's office. I tell her everything. I talk about all the stresses I've been having at work, my fears about managing my gender transition, the fact that I've started cutting again for the first time in 25 years. I tell her about the strain my gender transition has placed on my family. I tell her about the panic attacks that I've been having with increasing frequency, that I've been jumping out of my skin at the smallest things. I tell her about the flashbacks. The fact that I am unfit for work isn't exactly difficult for her to discern, so she signs off on a long term medical certificate and together with my therapist we start working out a plan to help me pull myself together.*

<p align="center">~</p>

The thing about the freeze response, I realised later, is that it can be adaptive. Just lie back and take it, honey -- it'll hurt but this way you won't end up dead. Supposedly it's not a thing that men experience much (for them it's all fight or flight, or so they say), but to be honest I've had that reflex for as long as I can remember. One example that comes to mind is high school, when there was a six month period where I was bullied more severely than usual. The boys threw food at me, insulted and humiliated me pretty much every day. They locked me under a sink during the lunch break one time. I just accepted it, I didn't tell anyone what they were doing to me, and absolutely I didn't do anything to stop them. I froze, day in and day out, and I let it happen. The only time I put up any resistance was when they would hit me. That didn't happen all that often often, thankfully, but the threat was always there. 

Looking back, it's strange. Why didn't I resist? Why didn't I do something? I don't really know, but the thing is, you get used to it. It becomes "normal" to you. The constant dread is just how life is, and you don't question the unfairness of it.

To this day I don't know why they targeted me. I'm not entirely sure they even had a reason. I guess I was an easy target though. I was shy, feminine, and sensitive, not generally considered valuable attributes in a boy. I was never going to be the kid who fought back, and frankly I imagine things would have gone a lot worse for me if I had. The idea that bullies will stop if you stand up to them is, in my limited experience of trying, a lie. Instead, they double down. So I had nowhere to run to, no realistic way to fight, so I froze. It upsets me to say it, but I think freezing wasn't the worst strategy possible in that situation.

The frustrating thing though is that freezing whenever you are threatened is not a good strategy for life more generally. Realistically, I think it was pretty much an inevitability that this learned response was going to end up with me getting raped. I barely even blame my rapist anymore, not because I've forgiven her or lost my fear of her, but because I think she's more or less irrelevant to the story. Sexual predators are a dime a dozen, and if it hadn't been her it would have been someone else. 

<p align="center">~</p>

*The first month off work I don't do anything, really. I tinker with some code, I start exercising daily, I make a promise to change. I promise to stop drinking, to stop self-harming, and so far I've kept my promise. As I write this it is 90 days since I have touched alcohol or tried to harm myself in any way. My partner and I start putting in the work to repair the damage to our relationship that my transition has caused. My therapist and I discuss how to manage a gradual return to work, how to tackle the panic attacks and the generalised anxiety that has left me unable to undertake even simple tasks. We even start talking about the rape, a topic that I've refused to open up about for years.* 

<p align="center">~</p>

Therapy has helped me a lot in coming to terms with my rape. The flashbacks don't come to me as often as they used to, and I'm much less prone to blaming myself or feeling ashamed. The simple fact that I can say that "I was raped" without equivocating about it or trying to hide from the truth of that statement is new, and it is liberating in a way I never expected. But progress does not come easily, and I'm not as free of the flashbacks as I'd hoped. On twitter I see it described like [this](https://twitter.com/urfeministboss/status/1174134739541876736):

> Rape isn’t just a *one* time incident. It stays with you for the rest of your fucking life and just when you think you may be okay and over it (as much as you can be) some tiny fucking thing triggers your memory and your PTSD flashbacks commence.

There is so much truth in this. Sometimes the triggers are obvious -- a woman who looks too much like her, a perfume that smells too much like hers, an accent that sounds too close to hers -- but not always.

Sometimes it's a man wanting have a *calm, intellectual discussion* about sexual harassment, and you want to scream at him at the top of your lungs. He reminds you of all the men who have wanted to have that same fucking conversation with you before, and your suppressed anger sets off the memories. Or it's the second man who is fascinated by your emotional response to the first man, who wants to dissect it like the psychologist you were coerced into seeing wanted to dissect your self harm. Or maybe it's a third man putting the thread on public display to his large following because he finds it interesting, just because he can do it and there are no consequences for him. Maybe you remember how she put you on display for all the world to see, people grinning and giggling as she raped you in the street on a Saturday night.

Suddenly you're back there. The time on that street corner. The time against the chain link fence. The time in your own apartment. You're frozen again, disoriented, drugged. None of this is real. You *know* it's not real. It's not a hallucination for fuck's sake and you can *see* that you're sitting in front of your laptop safe in your own kitchen. You know this. You're not stupid. But it feels so intense, and the rising panic is very, very real and oh my god how is this asshole *still* yammering on about consequentialism and why won't he just stop talking? 

A few days later maybe you try to hint obliquely as to what had happened, gently suggesting to the boys that we should be careful about PTSD triggers. Maybe a fourth man appears out of nowhere to mock you, because laughing at other people's trauma is funny to men, apparently, and you remember how they laughed when you talked about feeling violated. You delete your comments and cry, and anyway none of it matters because the whole thing plays out with a new cast of characters a couple of weeks later, and you spend yet another weekend trapped in rape flashbacks, feeling like all the work you've put into recovery has been wasted, wondering if you're even making any progress at all.

<p align="center">~</p>

*The time away from work has helped, I think. I approach my department head with a plan and he likes it. I start coming into campus, one day a week, and it is so hard not to unravel. I catch sight of the UNSW library building towering over me, flinch, and for a moment I'm back in the hotel room in Johannesburg. I attend a professional development workshop and a man is talking about the use of coercive power in an academic setting and for a moment I can feel the chain link fence against my back as she undresses me, frozen in fear. I leave the workshop early, thinking I must look like such a flake. I cancel some other meetings, shamefully wondering if my colleagues think I'm lazy. Well, maybe next week will be easier, I think to myself.*

<p align="center">~</p>

The strangest part of it all, it seems to me, is the way everything starts to bleed together after a while. It becomes harder and harder to remember which things happened when. My memories of the rape -- or rapes, if we're counting each incident separately -- were always disorganised and fragmented, but they've become even less coherent over time. Too many replays, too many other events that have become associated with it in my recollections. A bitter realisation is that I would make a terrible witness. My memories are the only evidence that any of this ever happened, and those are a tangled mess of fact and fiction.

The rape flashbacks are now mixed in with graphic images of self harm. They're often real memories, like slicing my wrists open with a dull blade in the shower, but those events happened at a different time and for a different reason. Others are pure fiction. I'm fairly certain that I've never stabbed myself in the eyes with a kitchen knife, but that's a recurring image that I have at least once a week. It's confusing.

The hotel room in Johannesburg is mixed in there now. The drunk man on the 370 bus threatening to kill me and smashing his fist against my seat and slamming his feet into the roof off the bus, that one is mixed in there. Or the time an attractive woman signalled her interest in me and I'm thinking how am I *still fucking frozen after all these years*, confused about where my words have fled to. That's mixed in there too. 

Even so, most of the flashbacks have one thing in common. That chain link fence. That first time. Realising what she was doing to me. Knowing there's a taxi not 20 meters away away. What her hands on me felt like. My disgust at my fucking useless body automatically reacting to her touch, encouraging her and betraying me at the same time. My anger that my voice has gone. The dawning recognition that I am utterly, completely helpless.

<p align="center">~</p>

*Little by little, it gets better. I make it to campus most weeks, sometimes more than once. I only need the valium every few days. Strange as it sounds given how hard this year has been I'm more in control of emotions than I've ever been. I'm slowly learning how to assert my own boundaries, to not freeze, to not automatically defer or submit to the wants of others, to let go of the shame -- at least for a moment or two -- and accept that not all the terrible things are my fault, not my responsibility to fix. The memory of the chain link fence is still there, but I feel a little less trapped by the recollection than I once did.*

*I think it's a good sign.* 

<p align="center">~</p>

These days I find myself in the strangest position when people start talking about sexual assault. I don't hide the fact that I'm a trans woman, but at the same time I'm not all that keen on tattooing *"transsexual"* on my forehead. Besides, even when people know I'm trans, my appearance is feminine enough that I pass most of the time: people unconsciously treat me as one of the girls rather than one of the boys. So when -- inevitably -- sexual assault gets framed as a gendered issue, I have no idea what to say. 

So often in these discussions I see men pop up and say "yeah, well just imagine what it's like to feel the fear of false accusation" and I think, yeah dude, I know. I've been there. I had a doctor once suspect me of sexually abusing my daughter, and it was a pretty awful experience. Compared to being raped though? Not a big deal. Trust me on this.

Or they will pop up and say "but what about when women are the rapists?" or "what about the male rape victims?" and I think well yeah that was actually me. What I've learned about men who say these things though is that the *only* time they ever express any concern for male survivors is when they're arguing against women. They're *never* the people stepping forward and standing up for male survivors in any other situation. They didn't give a fuck about my rape when they saw me as a man, and they still don't give a fuck about it now that they see me as a woman. It's just a debating point to them. 

The terrible thing about these men is that they don't realise that they are the bad guys. They believe with every fibre of their being that they are one of the [good ones](https://www.youtube.com/watch?v=OEPsqFLhHBc) and nothing will ever shake that belief. It doesn't matter that the only thing they ever *do* is argue with women and it doesn't matter that their obstinate refusal to listen and their terrible choice of words sets off flashbacks for the rape survivor sitting next to them. They *know* they are the good men, so they never change. Men who talk like this are not to be taken seriously, not for a second, because they are never arguing in good faith.

Maybe the worst thing about being a trans woman in these discussions though is that I remember how men talk when there are no women around. How casually they make rape jokes, how much they resent having to take sexual harassment training at work, how they think that #MeToo has gone too far. But I've lived as a woman long enough to know how women talk when there are no men around. Anonymous stories about the rapists who got away with it, whispered warnings about the missing stair, quiet support to help one another escape abusive situations. 

These worlds are so strikingly different. I sometimes feel like I'm living in a very traditional household from a bygone era. We have a nice dinner together and everyone is polite. Then the men go off to the lounge room and it's all fun and games, and the women do the kitchen work and trade in desperate stories of life and death. And we all accept this as normal.

<p align="center"><a href="https://www.theatlantic.com/past/docs/unbound/poetry/antholog/szymbors/stats.htm">~</a></p>

<!--
>
>A WORD ON STATISTICS
>
>by Wislawa Szymborska <br>
>(translated from the Polish by Joanna Trzeciak)
>
>Out of every hundred people,<br>
>those who always know better:<br>
>fifty-two.
>
>Unsure of every step:<br>
>almost all the rest.
>
>Ready to help,<br>
>if it doesn’t take long:<br>
>forty-nine.
>
>Always good,<br>
>because they cannot be otherwise:<br>
>four — well, maybe five.
>
>Able to admire without envy:<br>
>eighteen.
>
>Led to error<br>
>by youth (which passes):<br>
>sixty, plus or minus.
>
>Those not to be messed with:<br>
>four-and-forty.
>
>Living in constant fear<br>
>of someone or something:<br>
>seventy-seven.
>
>Capable of happiness:<br>
>twenty-some-odd at most.
>
>Harmless alone,<br>
>turning savage in crowds:<br>
>more than half, for sure.
>
>Cruel<br>
>when forced by circumstances:<br>
>it’s better not to know,<br>
>not even approximately.
>
>Wise in hindsight:<br>
>not many more<br>
>than wise in foresight.
>
>Getting nothing out of life except things:<br>
>thirty<br>
>(though I would like to be wrong).
>
>Balled up in pain<br>
>and without a flashlight in the dark:<br>
>eighty-three, sooner or later.
>
>Those who are just:<br>
>quite a few, thirty-five.
>
>But if it takes effort to understand:<br>
>three.
>
>Worthy of empathy:<br>
>ninety-nine.
>
>Mortal:<br>
>one hundred out of one hundred —<br>
>a figure that has never varied yet.
>
-->
