---
title: Ain't I a woman?
author: Danielle Navarro
date: '2019-02-14'
slug: aint-i-a-woman
summary: "For the longest time one of my favourite lines in feminist history came from the famous speech by Sojourner Truth. I learned recently that my understanding of the speech was mistaken, and have been pondering what lessons I should take from that."
---

For the longest time, one of my favourite lines in feminist history came from Sojourner Truth's 1851 speech, [Ain't I A Woman?](https://en.wikipedia.org/wiki/Ain%27t_I_a_Woman%3F)

> Dat man ober dar say dat womin needs to be helped into carriages, and lifted ober ditches, and to hab de best place everywhar. Nobody eber helps me into carriages, or ober mud-puddles, or gibs me any best place! And a'n't I a woman?

The idea of course being that women's liberation, as it had often been construed at the time, wasn't really about the liberation of all women - it was focused very narrowly on the rights of affluent white women. Yet, as per the speech, a black woman has no less a right than a white woman to demand her liberation. After all, *"ain't I a woman also?"* Shouldn't her rights as a black woman be as important as those of a white woman?

More recently, I learned that the version of the speech that I'd originally read isn't a particularly accurate transcription. [Sojourner Truth](https://en.wikipedia.org/wiki/Sojourner_Truth) didn't speak with a Southern dialect - she grew up in New York and her first language was Dutch. The version I read was written by a white woman,  [Frances Dana Barker Gage](https://en.wikipedia.org/wiki/Frances_Dana_Barker_Gage), who appears to have added quite a lot of content to the speech, with a certain amount of ... shall we say poetic licence? ... being taken. An earlier transcript of the speech writes doesn't include the refrain *"ain't I a woman?"* at all:

> I want to say a few words about this matter. I am a woman's rights. [*sic*] I have as much muscle as any man, and can do as much work as any man. I have plowed and reaped and husked and chopped and mowed, and can any man do more than that? I have heard much about the sexes being equal. I can carry as much as any man, and can eat as much too, if I can get it. I am as strong as any man that is now. As for intellect, all I can say is, if a woman have a pint, and a man a quart – why can't she have her little pint full?

What then of the phrase?

> And ain't I a woman?

If Sojourner Truth did indeed ask this question, the answer is self-evident - of course she is a woman, and her rights matter no less than those of a white woman. Yet the question now carries ambiguity. Did she intend the audience to make the comparison between white and black women, or was that something that a white woman added later?

As a trans woman reading this history, the ambiguity in this question seems so terribly relevant now. Ain't I a woman? I've been raped like a woman, I've been beaten like one, I've been treated just like a woman in so many ways that no woman deserves to be treated. So often I find that telling this side to my story gives me an immediate "pass" - my testimonials to the misogynistic treatment I've received *are* often considered sufficient credentials to be considered "really" one of the girls. But what does that matter? If a man - cisgender or trans - were to be treated so would that automatically make *him* a woman? It does not seem to be so, and it would be disrespectful to do so. It seems disrespectful to women to define them (or us, should I be considered a part of the club) solely by reference to a shared oppression. 

Should a woman be defined biologically? It is difficult to observe chromosomes, and we so often resort to anatomy as the basis for such decisions. I do not have a uterus or vagina, but my breasts are very real, grown using the same biological machinery as any cis woman's, and men stare at them no less. My testosterone is gone, my body hair is gone, and my voice is as ambiguous now as it always was. Regardless of my biology, though, no woman I have ever met has ever wanted to be *defined* in such terms. To be construed as nothing but a collection of sexual parts with a person attached is a terrible act of dehumanisation, and not one I would wish upon anyone. 

Am I a woman because I *feel* like I am or should be one? It seems like an answer, but not a great one. My gender is not directly accessible like pain, or fear, or joy. It is not sensory, or even particularly intellectual. At best I can describe it only indirectly, as a sense of *familiarity* with my own reflection when I saw it begin to change. The more I looked like a woman in the mirror, the more I recognised the reflection as my own. The more people treated me *as if* I were a woman - even when that has led them to be vile to me - the more I felt like they were interacting with *me*, and not with the shell of a man I've spent a lifetime hiding behind. 

Is that enough to be a woman? Metaphysically, I cannot answer the question. At such an abstract level I cannot say what makes a woman a woman, and I lack the intellectual arrogance to try. All I can say is that it gives me comfort and relief to be accepted *as if* I am a woman. In many respects I am tired of even asking the question of what I *really* am. Indeed, I would like to argue that it doesn't matter what I really am - the question is ill posed. All that matters is what rights, opportunities and affordances society will offer me. In this respect I take great comfort from reading the words of Andrea Dworkin, back in 1974, who - as a radical feminist of no small stature - wrote this 

> There is no doubt that in the culture of male-female discreteness, transsexuality is a disaster for the individual transsexual. Every transsexual, white, black, man, woman, rich, poor, is in a state of primary emergency as a transsexual. There are 3 crucial points here. One, every transsexual has the right to survival on his/her own terms.

The full text of her monograph *Woman Hating*, is well worth the read and as a transsexual woman myself, I am grateful for her words. Because this is all I have ever wanted or asked for - the right to survival on my own terms. 

A little bitterly, perhaps, I note that it is more often cisgender people who are fond of making blanket assertions that *"trans women are real women"* or similar. I suppose I do not disagree with these claims - after all, I feel I do live as a woman and have inherited many of the same concerns as cisgender women, albeit with a great many peculiarities that stem from my transgender history - but I tire of the idea that this is the right question to ask. Even if my status as a woman is artificial, even if I allowed to be who I am only as *"an emergency measure for an emergency condition"* - as Dworkin puts it - isn't that enough? 

Personally, I have become tired of the comparisons and contrasts that are often drawn between trans women and cis women. I am not sure it is a particularly helpful way to think about gender, and I think it tends to set women at odds with one another. In truth I want no more than the opportunity to live openly as myself, and be treated with a minimum of kindness and dignity. Am I not woman enough to ask that? 



