---
title: Emotional hurricanes
author: Danielle Navarro
date: '2020-09-12'
slug: emotional-hurricanes
summary: "On the occasion of my 43rd birthday, perhaps the most difficult admission I have ever had to make: I suffer from borderline personality disorder."
type: post
---

My emotional temperament has never been particularly stable. One of my earliest memories as a child is my father talking to me about how I overreact to everything. I was too happy over little things, too angry about minor annoyances, too distressed by small setbacks. A small thing would happen and my emotions would flare up intensely, uncontrollably, and the mood would be persistent. Especially the negative emotions: those simply would not settle down again quickly. Everything I felt, I felt with an intensity that burned through every attempt to contain it.

As I grew older my ability to control the outward expression of my emotions improved a little, but the emotional temperament itself did not change. It did not serve me well. In high school I was an easy target for bullying. Perhaps unfortunately, this interacted rather badly with the strategies I'd learned to cope with my emotions: whenever something happened, regardless of the severity of the thing itself, I would be flooded with emotions that I could barely control and I would "freeze". I'd would not react, I'd meekly accept what was happening. It was a self defence mechanism: shutting down completely was the only way I could stop the emotional hurricane from coming out, and nothing was more distressing to me than the prospect of letting the intensity of my rage and terror loose. It didn't seem to matter much what the inciting event was: I reacted to small things like teasing and kids throwing food at me the same way I handled bigger things like beatings and being locked in a cupboard. 

By the time I went to university I'd gotten a little better at self-control, and of course the people around me were a little more mature. I was no longer a target for bullying. I'd still get teased from time to time (who doesn't?) and I would still struggle with the emotional storm that followed but much less of it was visible from the outside. To the world I simply looked like a grumpy, depressed person. On the inside it was pure chaos. I'd go weeks without showing up to class, never telling anyone. But in my calmer days I would make up the lost time, and I got good grades anyway so my spotty attendance was rately noticed. Similarly, no-one noticed my alcoholism -- I'd started drinking quite heavily at age 12, but I was pretty good at hiding it so my parents only discovered it when I was 15, and so by the time I made it to university it firmly established -- against the general backdrop of binge drinking that is university life, it seemed unremarkable. I coped, I survived, and my experience has been that as long as you do the job in front of you and don't make a fuss, no one ever looks closely enough to see that you're falling to pieces. Even the persistent cutting and self-harm went unnoticed for months, whereupon I got caught by the administrators of the residential college where I was living.

Fast forward several years to my experiences in graduate school and the same pattern emerged. Minor setbacks weren't easy for me to cope with, and despite my best effort to keep the emotional hurricane contained, some of it leaked out and I wasn't always the most straightforward of students to deal with. Still, I got the job done, and my best guess is that my supervisor probably didn't think I was anything other than "somewhat insecure" (I never really asked him). The worst part though is that I never really learned a better method of coping than freezing. Freezing works as a strategy when nothing terrible is actually happening and your wild emotions are objectively miscalibrated; it's an appallingly bad strategy when you encounter a predator. Long story short, that one ended in rape.

It seems to me that this has been a consistent pattern, one that has continued into adulthood. Intellectually it's not difficult to spot, it just takes a lot of honest self-reflection and a little courage to do. The admission that this pattern is grossly typical of so-called ["quiet" borderlines](https://www.eggshelltherapy.com/quiet-bpd/) is one that sits uncomfortably with me, but I think it is correct.

<p align="center">~~~~</p>

Human mental life is complicated, however. Thoughts and emotions are tangled together and each responds to the other. I've known ever since early childhood that my emotional temperament was less than ideal, and I learned to hate myself for that. I berated myself severely for every miscalibrated emotion. I became ashamed of my emotional nature. I learned to hate myself, viscerally and deeply. I became timid and shy, afraid to venture into any situation that might provoke another emotional storm.

There were other consequences. Being beaten has an impact on the psyche, even if it doesn't happen very often. Suicidal thoughts and self-harm are, in and of themselves, deeply distressing things that have consequences. And I probably don't need to explain why, but being raped is more than a little traumatising -- it is one of the more common causes of post traumatic stress disorder. 

In other words, an unhealthy feedback loop developed that -- I think -- has resulted in other secondary mental health problems that aren't themselves borderline personality disorder. True, the root cause for all these events was probably my unstable emotional temperament, but I'm not a believer in original sin either as a religious doctrine or a psychoanalytic one. I can recognise that there is something inherent to me that placed me in those situations, but the blame for what happened does not inhere to me. The blame for my rape falls entirely on my rapist, and the blame for my bullying falls on my bullies. The self-harm I'll own -- that one is on me -- but I won't accept responsibility for the behaviour of the administrator who forced me to put on a suit and go to the formal dance while my wrists were still bleeding. In each case the people who harmed me were autonomous moral agents and as I look back on those experiences decades later I am no longer willing to excuse their actions.

Of course, these belated realisations are something of a cold comfort. The fact that I now understand the mechanism by which these things happened does not change the reality that they did happen, and they did harm. I still have rape flashbacks, which are more indicative of post-traumatic stress disorder than of borderline personality disorder. I still have nightmares of being locked in that cupboard. I have a phobia of knives and recurrent graphic thoughts of self harm, the cause of which is not exactly difficult to diagnose. I think of these mental health issues as conceptually distinct from the emotional dysregulation problem itself.

Nevertheless, with age comes some wisdom at least, and I've been sensible enough to seek therapy for these issues. They haven't all disappeared, not by any stretch of the imagination, but I'm showing improvement on all of those fronts. The flashbacks and intrusive thoughts are rarer than they were 12 months ago and the panic attacks are almost entirely gone. I haven't touched alcohol in 14 months, and my anxiety has reached the point that I'm only forced to use valium or ativan once a month. It is hard work to make any progress but I can see that -- in these respects at least -- I am genuinely getting better, and I think that recovery from those "secondary" health problems is a matter of being patient and continuing to do the work.

<p align="center">~~~~</p>

My emotional regulation problems are a little different. From some amount of introspection and reading, I don't think it is at all likely that the emotional temperament itself is malleable. It hasn't moved at all in 43 years, and the literature on borderline personality disorder seems to agree with my general feeling that the emotional torture itself will never end. Emotional storms are something I will simply have to accept. There is very little I can do to prevent one, and once it has started there is very little I can do to force it to stop. The underlying emotional dysregulation is so severe that no amount of reasoning, no self-talk, no cute little self-soothing technique can stop it. The storm will come and it will wreak havoc no matter what. It makes no more sense to berate myself for failing to prevent the emotional flood than it does to blaming myself for being unable to verbally persuade a hurricane to transform into a gentle breeze. For good or ill, this is inherent to me. The shame and self-loathing I feel about this fact is pointless. 

Acceptance of that fact is not an admission that all is hopeless. For the last few weeks, ever since I started taking this seriously and absented myself from the emotional cauldron that is twitter -- where my self-control fails me entirely and I have a disheartening tendency to slide into "classic BPD" behaviour -- I've been consciously exploring the scope of my emotional responses and testing different strategies to regulate their expression. It has been instructive to say the least. I'd thought that I had strong emotions before, but in the course of the last couple of weeks as I've simply allowed myself to feel whatever I feel without attempting to force it to stop ... it is so much more intense than I ever realised. An ambiguously worded remark ought to be at most the source of a moment's fleeting concern; instead it induces overwhelming terror that does not dissipate. Listening to a showtune I'd not heard before ought to be mildly pleasing; instead it is excruciating, intense, exciting, overwhelming, rapturous. It is like drugs. It is like sex. To steal Trent Reznor's words from "Closer", the subjective feel of the emotion is so strong that it *tears down my reason* ... and all this because Hugh Jackman is kind of attractive, has a fabulous voice, and because I *didn't* engage my automatic emotional lockdown mechanism the moment I detected a feeling. 

Oof.

This is, to say the least, impractical. 

<p align="center">~~~~</p>

I am not without recourse. The [serenity prayer](https://en.wikipedia.org/wiki/Serenity_Prayer) is instructive in this respect. It does not counsel hopelessness or self-deception. It exhorts us to use the tools that we have, to exert control where we can. What I cannot control is the emotional cyclone. It will happen and I need to accept it. What I can control is my behaviour. I can minimise my exposure to the worst triggers, I can withdraw from the world when I need time to let the storms pass, and I can mentally "batten down the hatches" to endure without self-harm. I'll probably have a go at [dialectical behaviour therapy](https://dialecticalbehaviortherapy.com/) -- it seems to be focused on practical skills I can deploy rather than unrealistically attempting to modify the emotions themselves.

<p align="center">~~~~</p>

I'm not as sanguine about this as my post so far suggests. Truth be told I'm getting rather tired of accruing mental illness diagnoses. Mental health is not a fucking stamp collection, and the goal of the bloody exercise is to get rid of the problems not add new ones to the list. Sheesh. I mean, if we stipulate that the borderline diagnosis is correct, my list of conditions is now:

- gender dysphoria (duh!)
- depression (severe)
- generalised anxiety (moderate/severe)
- post traumatic stress disorder (moderate/severe)
- borderline personality disorder

Thrilling. I can barely contain myself with joy.


The prospect of a borderline personality disorder diagnosis makes me uncomfortable. In part I'm being petty: intimate partners have suggested this to me before and frankly I'm a bit irritated at them for being right. But there's more than mere petulance. The stereotype about people with borderline personality disorder is *highly* stigmatising. Far more so than any other mental health problem I've had to deal with. It's even worse than gender dysphoria that way: to be borderline is to have people presume you are manipulative, irrational, insecure, and unstable. Social licence is now granted to assume that I am merely a crazy irrational bitch and not listen to a word I say on any topic. It's a medical fact! 

It doesn't matter that this isn't really a fair characterisation of borderline personality disorder, and it doesn't matter that it is grossly unfair to us -- this is what people assume. When I voiced this fear in the past I've heard people say "no no that's not what I think at all..." but come on people. I am not stupid. I have eyes. To try to suggest to me that this *isn't* how borderline personality disorder is perceived is an insult to my intelligence. 

Noting this, my worry about BPD is that it's something that undermines people's trust in you -- in a he says/she says scenario who should you believe, the respectable man or his borderline ex-girlfriend? BPD is a credibility-killer. All else being equal, we believe the person without BPD over the person with BPD. The same isn't true for depression or anxiety. I think there's an element of it with regards to PTSD sufferers, and there's certainly some of it going on for gender dysphoria. But my fear is that this will be much more severe for BPD. 

To publicly acknowledge that I am borderline -- after already having come out as a trans woman and publicly transitioned? -- anyone and everyone will have a reason to dismiss my emotions as irrational or an overreaction no matter what the context may be, and for the life of me I cannot think of a way that I could contest such a claim.

That terrifies me.

