---
title: A subjective impression
author: Danielle Navarro
date: '2020-08-15'
slug: a-subjective-impression
summary: "A few remarks on gender dysphoria"
type: post
---

[This post is a work in progress]

I'm not exactly sure when I started transitioning, in part because I'm not sure how to define the term. Intuitively it seems to me that gender transition begins not when you come out to yourself, or even to others. Rather when you start taking public action that begins a permanent shift. It's one thing to admit to yourself that you are transgender, quite another to actually do something about it: deliberately, of your own volition, and with the intent to make a permanent change. To my way of thinking, coming out is the first part, transitioning is the second part. Even with that distinction in mind, it's pretty hard to pick a moment. I could date it all the way back to some of my gender nonconforming attire back in 2002 but that seems silly. A slightly more plausible answer might be 2013 when I started trying out gender nonconformity in more of a deliberate fashion from time to time, but it wasn't public. The first thing I can think of that meets the criteria I listed above would be when I started deliberately feminising my appearance at work, in full knowledge of why I was doing it. The internet being what it is, I can track down the date it started: early in August 2016. So it's been almost exactly four years now, and it seems as good a moment as any to try to describe my experience of gender dysphoria.

<p align="center">:::: :</p>

A natural place to start might be to talk about mental illness. In the 42 years I've been alive, I've been forced to acknowledge mental illness in myself more than once. Depression and anxiety have been constant, reliable companions. In my interactions with the mental health system I've managed to accrue a variety of diagnoses, some of which I think are accurate, others that I don't. Major depression, generalised anxiety, panic disorder, post traumatic stress disorder, etc. I'm not sure that I put a lot of faith in the specific labels, but it's not unreasonable to say I've had persistent mental health difficulties for most of my adult life. I'm quite open about it, and have reached the point where I don't feel much stigma or shame about any of that stuff anymore; I'd rather devote my time and energy to managing the conditions.

With that as a preliminary I think it helps to talk a little about the relationship between gender dysphoria and mental illness. When I was younger, the relevant diagnosis (per DSM IV) was called Gender Identity Disorder, and it framed transgender identities as inherently disordered: being trans was in itself a classified as a mental illness. In 2013, with the release of DSM V, this changed. The name of the condition was changed to Gender Dysphoria, and the definition altered such that being transgender was not in itself defined as disordered; instead, it is only the distress, depression and anxiety that a person experiences as a consequence that is considered a problem - but that distress can be quite severe sometimes. So while being transgender is not itself considered a disorder anymore, there are enough idiosyncratic feature to gender dysphoria that it warrants its own entry in the DSM. 

Writing about gender dysphoria is not a straightforward exercise. For one thing, there aren't many of us who experience it, and historically we have not been treated with kindness when we discuss it. For another, it's an experience that most people find quite alien, and so while there are many people who are sympathetic to us, it isn't easy for others to empathise. 

I'll try my best to describe my own experience. 

<p align="center">:::: :</p>

Perhaps it will be a little easier to start with some remarks about what my gender dysphoria *doesn't* feel like. There are a lot of euphemisms or oversimplified stories that I read and while many of them have a grain of truth in them I also think they can be a little misleading. Without wanting to make any claims about what other people feel -- because obviously I have no idea what it feels like to them -- I don't find any of the euphemisms very compelling.


First: I don't feel like I was "born in the wrong body". Quite clearly this is my body and while I hate the damned thing I can't really think of what it would mean to be born in the wrong one. That phrase doesn't mean anything to me.

Second: I don't "feel like a woman" either. That makes even less sense to me. I feel like ... me? That's kind of all there is to it. At best I might say there's a sense in which it feels like I "should have" been born a woman, that I'd have been a lot fucking happier from the beginning if I had a body like that rather than one like this. That kind of makes sense to me, though it's a bit peculiar because any reasonable interpretation of the way the world works suggests that women get the short end of the stick. Regardless, it doesn't seem to make sense to me to claim that "I feel like a woman". That just sounds like a Shania Twain song.

Third: this doesn't feel like a "gender performance" either. I find that framing insulting. I found an old article from [Julia Serano](https://jezebel.com/gender-is-not-just-a-performance-5647120) that captures my feelings on that particular topic nicely: 

> performance doesn't explain why certain behaviors and ways of being come to me more naturally than others. It offers no insight into the countless restless nights I spent as a pre-teen wrestling with the inexplicable feeling that I should be female. It doesn't capture the very real physical and emotional changes that I experienced when I hormonally transitioned from testosterone to estrogen. Performance doesn't even begin to address the fact that, during my transition, I acted the same, wore the same T-shirts, jeans, and sneakers that I always had, yet once other people started reading me as female, they began treating me very differently. When we talk about my gender as though it were a performance, we let the audience — with all their expectations, prejudices, and presumptions — completely off the hook. 

Fourth: I don't think it's a delusion. I'm painfully aware of what body I have, and the biological implications of that fact. To my mind, for my gender dysphoria to constitute a delusion there should be some sense in which I should no longer be trusted to provide an honest and reliable description of my own experience. Or, more precisely, that should be more true of me than it is of everyone else: we are all, to an extent, unreliable narrators vulnerable to a variety of perceptual and cognitive illusions. Psychologists have documented quite a lot of effects that would fall into that category, and I'm no less susceptible to them than anyone else, but the term "delusional" carries a much stronger connotation. My gender dysphoria is *weird*, certainly, and I'll be the first to concede that it's a strange situation to find yourself in. Equally, I'm obviously not exactly in the majority for feeling like this: there's clearly something about me that isn't the same as most people. But as far as I can tell there's nothing in what I've written here or elsewhere that suggests I have lost the faculty of reason or cannot trust my perception of the world?

I'll return to the subject of "delusion" in a moment, because I think this particular preconception that many people have interacts with actual gender dysphoria in a very nasty way sometimes.

<p align="center">:::: :</p>

If these phrases don't capture my experience, what does?

The best -- or perhaps "least bad" -- way to describe it that I can come up with is that for a long time I have had a sense of distress associated with my sexed body. What I mean by this is that I have always disliked having a penis, and I loathed all the changes that happened to my body during puberty. The process of developing male secondary sexual characteristics felt like body horror to me, and I didn't know why I felt that way. 

What I did notice -- eventually -- is that my body felt less gross to me in situations where I was able to appear feminine. Anything I was able to do to counteract the perceived masculinity of my body made it a little easier to tolerate that body. At the time I felt ashamed of that: men aren't supposed to be feminine, after all. There was then (and perhaps still is) rather a lot of stigma associated with feminine men. For most of my life, then, I have considered myself a feminine man, but one who was a little too afraid to let much of that femininity show. 

That when I started transitioning, I felt a sense of "familiarity" with my own reflection that hadn't been there before? Or maybe just this low-grade sense of disgust I used to have had disappeared? Something like that anyway. The point is that every time I took a step in the direction of transitioning, of changing my body, my behaviour and my attire, I felt a sense of relief and comfort. Any time I considered going back, I felt dread and disgust. As far as I can tell, it was those emotional responses that drove my transition.


<p align="center">:::: :</p>

Although it has taken me four years to reach this point, the process of transition felt remarkably fast. Too fast. Being a statistician of sorts the metaphor I use is that of a stochastic optimisation algorithm or perhaps an MCMC chain. Imagine for a moment that there is some notion of a "gender space" in which each point corresponds to some combination of public presentation accompanied by some internal mental model of what kind of person I am, and the complete space is the set of possible mental representations and behaviours. This is of course absurdly vague, and I don't know what that would actually mean in real life either: it's an analogy, not an isomorphism. Sheesh.

In any case, according to this analogy there would exist a function that describes my level of comfort or discomfort with occupying any given location. Every time I take an action or choose to think about myself a different way, I move a tiny distance in this space. It either makes me feel better, or feel worse. When something feels better, I am more likely to adopt it in the future; when it feels worse I am less likely to. Over time, I trace out a trajectory.

What it feels like to me is that the "familiarity" signal I talked about in the previous section played a big role in driving this trajectory. Any step in which I acted a little more feminine or altered my mental model of myself to acknowledge this femininity felt more "genuine" (if that makes sense?). I would see myself in the mirror and the person I saw in the reflection was easier for me to look at, easier to recognise and acknowledge as me. Any attempt to move in the other direction was almost physically painful. Despite my best efforts not to transition, it just sort of happened... the drift on this cognitive and behavioural trajectory was highly non-random. And so here I am now. 


<p align="center">:::: :</p>

Comments written about me on twitter in the last couple of days.

> you are definitely a guy ... you are a guy who for whatever reason thinks he's a girl ... it has to do with reality ... people are encouraging you ... people are telling you what you want to hear, not what you need to hear ... its REALITY ... if you can't grow out of those sorts of things, you'll never be an adult ... back in the day those people would be in mental care facilities

In my experience, there aren't many people who are willing to say these things directly to my face, even on twitter. Most people are actually quite nice to me. That being said, there are quite a lot of people who say exactly this kind of thing (and more) on twitter and on other websites. Quite clearly, when they aren't talking directly to me, there are a lot of extraordinarily horrible things some people will say about people like me. 

It is a small mercy that few people say such things to my face, but it is something of a mixed blessing. I mentioned I have anxiety. The obnoxious things that people sometimes *do* say to me are so eerily similar to my worst fears, and so similar to the unpleasant things I see people saying in other places, that I start wondering. Maybe those comments are right:

> you are definitely a guy ... you are a guy who for whatever reason thinks he's a girl ... it has to do with reality ... people are encouraging you ... people are telling you what you want to hear, not what you need to hear ... its REALITY ... if you can't grow out of those sorts of things, you'll never be an adult ... back in the day those people would be in mental care facilities

This time around it's not *them* saying it, it's me. It's trivially easy to deal with one minor troll on twitter saying nasty things; it's a lot harder when it's not a twitter troll but all your personal demons telling you the same story. All those fears I mentioned at the beginning of the essay now come into play:

Perhaps my perception of myself and the world is irredeemably flawed. Perhaps everything I wrote above about how my transition unfolded is a comforting lie I have told myself. Maybe I should be in a mental care facility: can I really be trusted to exercise my own autonomy? Maybe ... maybe I truly am delusional?

<p align="center">::::: :</p>

I talked about this fear on twitter, and I'll expand on it here. 

My fear stems from having grown up in a world where it was accepted as "obvious truth" that people like me are inherently disordered & the simple fact of being transgender was prima facie evidence of delusion. We could *never* be trusted to be rational. This worldview has changed, but only recently. Even 10 years ago (when I was 32) it was still widely accepted that being transgender *is* a mental illness. That world view is still very common, and it is still in my head just as much as everyone else of my generation. 

When a random troll appears on twitter or [elsewhere](https://statmodeling.stat.columbia.edu/2020/07/21/male-bisexuality-gets-big-pnas-energy/#comment-1389837) to make some silly and childish remark about trans people being mentally ill, or when I see academics writing articles, posts and tweets -- recent examples [here](https://twitter.com/SwipeWright/status/1293326796713160704), [here](https://twitter.com/normfinkelstein/status/1292842046387101696), [here](https://www.theaustralian.com.au/inquirer/few-female-engineers-its-a-matter-of-choice/news-story/5c9a4d58ddf7656a0920d597d413339b) and [here](https://medium.com/@aytchellis/trans-men-are-men-but-transwomen-are-not-women-7ba7a533e8a5), but honestly these things are a constant stream and these examples are neither remarkable or unusual -- that dispute or deliberately undermine the validity of transgender identities, it has a larger effect on me than merely "hurting my feelings". It makes me question my sanity.

Because I am trans, these things are sent to me by friends, colleagues, etc and I necessarily get dragged into things I'd prefer not to. Worse yet, because I am a trans woman, almost all of these things target people like me specifically. The vast majority of anti-trans sentiment is directed at trans women, and being the target of this that has a severely negative effect on my mental health. As an example, I've just spent three weeks arguing patiently with a colleague -- trying my best to hold back my own fear -- that some of the things he's written about us in national newspapers are unkind (it was a follow up to [this post](/post/on-small-differences/)). I think I convinced him in the end, but I won't lie, it came at a dreadful personal cost. 


Not by choice then, my everyday environment is one in which I am constantly exposed to material that mocks me, humiliates me and asserts that I am delusional; and every day I remember what the world used to be like and the world view I was raised with. I see a world in which my very sanity is considered a debatable subject. But everyone around me don't have the same exposure to this kind of content, and the don't carry around the same fears and insecurities that I do.

So what happens is this cycle. I see something that causes distress and I try to ask for help (sometimes on Twitter). Other people don't see any of the surrounding history or context and they shrug it off and say "just ignore it -- they're just trolls". This throws me for a loop. From my perspective I am struggling to believe that I am sane, that I am not delusional simply because I am transgender. I ask people for help and everyone seems ... indifferent to the level of terror I feel.

So what should I make of all this? Is it me (one person) misreading the world or is is it you (many, many people)? Ockham's razor suggests it is me. That I am wrong, that I am unable to correctly perceive the state of the world ... in other words, that I am delusional.

From that point it spirals. I have no reference point to determine whether my own reason is trustworthy and every signal I am getting from my friends, my family, my peers suggests that I am in fact, delusional. In short there is a mechanism by with other people's silence (which to me is quite conspicuous) reinforces my fear that I should not trust my own perception of the world. So if you genuinely believe that I am not delusional, and you don't want to contribute to the spiral that makes me believe that I am, I need people to be willing to say those words out loud -- because I have no reason to think my sanity is "obvious".


