---
title: Twitter redux
author: Danielle Navarro
date: '2020-09-23'
slug: twitter-redux
summary: "Thoughts on returning."
type: post
---

As I write this I have been on a twitter break for a little over three weeks, and am contemplating the possibility of returning. I am uncertain if I will. My therapist insists that social media is a bad idea in general, and wants me to quit entirely. My own feelings are a little more mixed, but he isn't entirely wrong -- for all the professional and personal benefits I've received from being on twitter, it has come at an immense personal cost. Twitter poses a real threat to my mental health, one I need to take seriously.

Truth be told, the problem isn't specific to twitter. A lot of the troublesome patterns that I encounter on twitter also occur in real life, and on other kinds of social media. But none of my other social media accounts have the same public visibility or the same close ties to my professional world. Neither do my other social media accounts bring me into such close contact with people who view me as contemptible for what I am, or people who treat my personal life as an extension of their political opinions. In that sense twitter has the capacity to be a uniquely destructive influence on my life. In terms of the role it plays in my life twitter is not analogous to instagram, it is analogous to alcohol: something highly addictive, potentially beneficial, fun when used with caution, extremely hazardous if misused. In the case of alcohol, I decided the benefits were not worth the costs and quit over a year ago. I'd be lying if I said I don't miss drinking, but I don't want to return to that part of my life at all and I firmly believe that was a wise choice. 

I'm still trying to make up my mind about twitter, and -- god help me -- I am going to try to clarify my thinking with a cost/benefit analysis. Well, as soon as I can stop rolling my eyes at myself.

### Benefits

- Posting art is inherently rewarding
- Interacting with R community is inherently rewarding
- It is where my friends are, and staying in touch is important to me
- I learn a lot of programming/art from twitter
- There are a lot of professional opportunities on twitter
- The ability to publicise projects, events etc is unparalleled
- Asserts my right to exist in public space (a personal matter)

### Costs

- Emotional demands are intense (especially given my situation/temperament)
- Context collapse is so severe that some subjects are impossible
- Twitter can absorb a lot of my time in unproductive ways 
- Political content induces hard-to-control emotional responses 
- Visibility as trans woman means proximity to anti-trans activists
- Academic twitter is viciously combative, and a real threat to my mental health

Looking at this list it seems to me that there are a lot of very substantial benefits (I can point to a lot of wonderful things in my personal and professional life that came about only through twitter) but equally there are a lot of large costs (there's a lot of pain buried in those dot points). What makes it difficult is that -- paraphrasing Stannis Baratheon -- the good does not wash away the bad, nor the bad the good. There is no moral or emotional calculus that I can articulate which would allow these things to be placed on a common scale, no simple way of weighing one against the other.

In light of my experiences this year, it seems to me that I can return to twitter *only* if I have a viable plan to reduce or eliminate these costs. The problem, as I see it, is that things have reached the point where the negatives are so bad that they are unmanageable, and no benefits can possibly "outweigh" them. The benefits are lovely, but I will happily sacrifice quite a lot of them in order to minimise my exposure to the negatives. Right now this has placed me in a position where I am not on twitter at all. It would be worth considering what kind of twitter presence I could have (given all of my givens) that would allow me to have some of those benefits while keeping the negatives to a bare minimum. 

So what would an "acceptable twitter presence" look like for me?

### Instructions to my future self

There are a handful of very strict rules to abide by. If you can't adhere to these at a bare minimum you need to quit twitter forever. 

0. **Always check this list before tweeting.**
1. No politics of **any** kind. This includes academic politics, culture wars, anything to do with trans rights. Yes you have political beliefs; you don't need to discuss them on twitter, and it is usually harmful to me when you do.
2. No academic talk about emotionally charged subjects. That includes open science, preregistration, and the logic of scientific inference. Discussion of these subjects on twitter is not possible: it has become a culture war in itself and accordingly, forbidden under rule 1.
3. Never tweet from negative emotion. Context collapse leads to emotional magnification on twitter, and that is particularly dangerous for you given the nature of your emotions. If you have even the slightest doubt about it, you do not post. Yes, that means **you** sweetie, right now. You can come back here tomorrow if you must. 
4. Limit tweets from positive emotion. Positive emotions are fine, but be wary of how the cascade works.
5. Enforce your time boundaries. Your "strictly managed login" method works as long as you adhere to the preceding rules during login, and it is the only thing that has. This strategy must stay in place. The upper bound on login is an hour in the morning and an hour in the evening. More than that and you risk cascade.