---
title: Meaningless questions do not have meaningful answers
author: Danielle Navarro
date: '2020-08-21'
slug: trans-women-are
summary: "I don't have an opinion about whether trans women are real women, any more than I have an estimate of the number of angels that can dance on the head of a pin or a belief about the mood of Thursday."
type: post
---

It is probably not difficult to infer that I dislike the phrase "trans women are women". In my post on [transgender rights](/post/an-ordinary-account), I took care to outline my opinions in a way that makes no reference to *any* claim about whether I am a "real woman". I have been consistent on this point for a long time: I do not think that the case for transgender rights rests on any such claim, so I do not and will not include it in any argument I make regarding the rights of transgender people.

Similarly when I wrote my post on why I [describe myself as a trans woman](/post/a-lexical-decision) and at times simply as a woman, I did not justify myself by making any claim about being a "real" woman. Even if my gender identity were a total fiction, in most cases we don't usually have a problem with calling fictional women "women" even though we would agree they are not real women. My willingness to use the word is not dependent on any strong metaphysical stance. You get the idea.

Nevertheless people do sometimes ask or expect me to take a position on this question. It irritates me: people ask me this question expecting that I will have a yes or no answer for them. I don't have one. I think it's an absurd and ambiguous question, and I can't give you a proper answer to it unless you are more precise about what you are asking me. There are lots of ways that you can make it more precise, and my answer is different in each case. With this in mind, the following brief Q&A attempts to summarise my thoughts.

<p align="center">::::::</p>

-   Do you think trans women should be treated as women? 
    
    **As a default, yes. My reasoning for this is outlined [here](/post/an-ordinary-account) and [here](/post/a-lexical-decision)**
    

-   Do you think there are situations where that default might not apply or not be appropriate?

    **Yes. Though it is often maligned, I am a firm believer in the practical value of [casuistry](https://en.wikipedia.org/wiki/Casuistry), and the specifics of the situation will call for different approaches in each case.**


-   Do you believe that a transgender woman is biologically female in the same sense that a cisgender woman is biologically female?

    **No.**


-   Do you believe facts about sex and reproductive biology should be considered relevant to discussions about gender? 

    **Yes.**

-   Do you believe facts about sex and reproductive biology are the *only* facts relevant to discussions about gender?

    **No.**
    
-   Do you believe that "being a woman" is a psychological state, solely a function of a person's feelings and sense of personal identity? 

    **No. Laws, cultural norms and biology matter.**


-   Are trans women are biologically male? (Stipulate good faith)

    **In some cases yes. In others, not necessarily. The biological sex characteristics for a transsexual woman such as myself are an odd mixture. For example, I (probably) have XY chromosomes, but I also have high oestrogen levels, and near zero testosterone. Plus, you know, I have breasts. These are all aspects of biological sex in humans, and that does matter. If you are discussing this subject in good faith you are not entitled to cherry pick the data: you cannot choose which sex characteristics are "legitimately" relevant to female sex solely for the purposes of excluding transsexual women from consideration. It is intellectually dishonest to do so.**

-   Are trans women biologically male? (Pretend this is twitter)

    **I think this is a trap. In almost every case I have seen this question asked, it is a prelude to a rhetorical pivot, in which the speaker no longer uses the term "trans women" in any context, and subsequently refers to trans women exclusively as "biological males". It often comprises one part of a motte and bailey argument used to justify misgendering, refusing to use appropriate pronouns, and more generally to be cruel to trans women. I have learned from bitter experience not to trust anyone who asks me this question. It is almost never asked in good faith.**

-   Are trans women natal males?

    **Yes. The term "natal males" refers to the sex registered at birth. My original birth certificate listed me as male, so I am a natal male.**

-   So it's okay to call trans women natal males?

    **Almost never. In almost every context the appropriate term is simply "trans woman". Using terms like "natal male" and "biological male" in everyday language as a way to avoid having to call us women is misgendering, pure and simple. The use case for the term "natal male" is pretty narrow, and mostly restricted to situations when precision is needed in academic or scientific contexts. Outside those contexts, it's completely inappropriate language.**

-   Do you support your trans sisters in their/our political fight for civil rights? 

    **Yes. Trans rights are human rights. This is fundamentally a political question about the civil rights of transgender people, not an academic debate about sex and gender.**


-   Are you a transmedicalist?

    **No. The transmedicalist position is much stronger than simply acknowledging nuances about biology. It is a political position in which transsexual people such as myself do not acknowledge the legitimacy of other members of the trans and gender diverse community. As a political stance I will not have any part of it and I repudiate it entirely.**


-   Do you believe trans women are "real women" in a metaphysical sense? 

    **Good grief, who cares about the metaphysics? I don't know and I regard it as a waste of my time to try to figure it out. Come back to me when I have spare time to waste on pointless questions.**

<p align="center">::::::</p>

Now let us never speak of this again. Meaningless questions do not have meaningful answers, and this one is about as meaningless as it gets. Either be clear about what you're asking me or go away and leave me alone.