---
title: Time to move over
author: Danielle Navarro
date: '2020-08-17'
slug: time-to-move-over
summary: "A few remarks on my experiences with gender dysphoria, transition, and being the unwilling participant in someone else's culture war; additionally, a resolution to withdraw my voice from a discussion that has done me too much harm already"
type: post
---

> I'm so tired of playing <br>
Playing with this bow and arrow <br>
Gonna give my heart away <br>
Leave it to the other girls to play <br> &nbsp;&nbsp; --Portishead

I'm not exactly sure when I started transitioning, in part because I'm not sure how to define the term. Intuitively it seems to me that gender transition begins not when you come out to yourself, or even to others. Rather, it begins when you start taking public actions -- however small they might be -- that mark a permanent change. It's one thing to admit to yourself that you are transgender, quite another to actually do something about it. To my way of thinking, coming out is the first part, transitioning is the second part. 

Even with that distinction in mind, it's pretty hard to pick a moment. I could date it all the way back to some of my gender nonconforming attire back in 2002 but that seems silly. A slightly more plausible answer might be 2013 when I started trying out gender nonconformity in more of a deliberate fashion from time to time, but it wasn't public. The first thing I can think of that meets the criteria I listed above would be when I started deliberately feminising my appearance at work, in full knowledge of why I was doing it. The internet being what it is, I can track down the date it started: early in August 2016. So it's been almost exactly four years now, and it seems as good a moment as any to try to describe my experience of gender dysphoria.

<p align="center">:::: :</p>

A natural place to start might be to talk about mental illness. In the 42 years I've been alive, I've been forced to acknowledge mental illness in myself more than once. Depression and anxiety have been constant, reliable companions. In my interactions with the mental health system I've managed to accrue a variety of diagnoses, some of which I think are accurate, others that I don't. Major depression, generalised anxiety, panic disorder, post traumatic stress disorder, etc. I'm not sure that I put a lot of faith in the specific labels, but it's not unreasonable to say I've had persistent mental health difficulties for most of my adult life. I'm quite open about it, and have reached the point where I don't feel much stigma or shame about any of that stuff anymore; I'd rather devote my time and energy to managing the conditions.

With that as a preliminary I think it helps to talk a little about the relationship between gender dysphoria and mental illness. When I was younger, the relevant diagnosis (per DSM IV) was called Gender Identity Disorder, and it framed transgender identities as inherently disordered: being trans was in itself a classified as a mental illness. In 2013, with the release of DSM V, this changed. The name of the condition was changed to Gender Dysphoria, and the definition altered such that being transgender was not in itself defined as disordered; instead, it is only the distress, depression and anxiety that a person experiences as a consequence that is considered a problem -- but that distress can be quite severe sometimes. So while being transgender is not itself considered a disorder anymore, there are enough idiosyncratic features to gender dysphoria that it warrants its own entry in the DSM. 

Writing about gender dysphoria is not a straightforward exercise. For one thing, there aren't many of us who experience it, and historically we have not been treated with kindness when we discuss it. For another, it's an experience that most people find quite alien, and so while there are many people who are sympathetic to us, it isn't easy for others to empathise. 

I'll try my best to describe my own experience. 

<p align="center">:::: :</p>

Perhaps it will be a little easier to start with some remarks about what my gender dysphoria *doesn't* feel like. There are a lot of euphemisms or oversimplified stories that I read and while many of them have a grain of truth in them I also think they can be a little misleading. Without wanting to make any claims about what other people feel -- because obviously I have no idea what it feels like to them -- I don't find any of the euphemisms very compelling.

1. I don't feel like I was "born in the wrong body". Quite clearly this is my body and while I hate the damned thing I can't really think of what it would mean to be born in the wrong one. That phrase doesn't mean anything to me.

2. I don't "feel like a woman" either. That makes even less sense to me. I feel like ... me? That's kind of all there is to it. At best I might say there's a sense in which it feels like I "should have" been born a woman, that I'd have been a lot fucking happier from the beginning if I had a body like that rather than one like this. That kind of makes sense to me, though it's a bit peculiar because any reasonable interpretation of the way the world works suggests that women get the short end of the stick. Regardless, it doesn't seem to make sense to me to claim that "I feel like a woman". That just sounds like a Shania Twain song.

3. I'm not doing a "gender performance". I find this oh-so-clever framing insulting, like someone has read a few passages from Judith Butler and decided those are sufficient to explain my life. I found an old article by [Julia Serano](https://jezebel.com/gender-is-not-just-a-performance-5647120) that captures my feelings on that particular topic nicely: 

    > performance doesn't explain why certain behaviors and ways of being come to me more naturally than others. It offers no insight into the countless restless nights I spent as a pre-teen wrestling with the inexplicable feeling that I should be female. It doesn't capture the very real physical and emotional changes that I experienced when I hormonally transitioned from testosterone to estrogen. Performance doesn't even begin to address the fact that, during my transition, I acted the same, wore the same T-shirts, jeans, and sneakers that I always had, yet once other people started reading me as female, they began treating me very differently. When we talk about my gender as though it were a performance, we let the audience — with all their expectations, prejudices, and presumptions — completely off the hook. 

   This. Early in transition I used to wear skirts and dresses quite a lot, but nowadays my attire is blue jeans, black t-shirt and boots. True, they're different to and more feminine than the blue jeans, black t-shirts and sneakers that I used to wear, but the truth is it's not my clothes that are changing how people perceive me -- I'd be more inclined to attribute causality to, you know, my breasts? Whatever else you might think of them, they are most definitely not mere performance.

4. A part of me wishes desperately that I didn't feel the need to argue this one, but I don't think it's a delusion. I'm painfully aware of what body I have, and the biological implications of that fact. To my mind, for my gender dysphoria to constitute a delusion there should be some sense in which I should no longer be trusted to provide an honest and reliable description of my own experience. Or, more precisely, that should be more true of me than it is of everyone else: we are all, to an extent, unreliable narrators vulnerable to a variety of perceptual and cognitive illusions. Psychologists have documented quite a lot of effects that would fall into that category, and I'm no less susceptible to them than anyone else, but the term "delusional" carries a much stronger connotation that I don't think is fair. My gender dysphoria is *weird*, that much I will grant. But as far as I can tell there's nothing in what I've written here (or elsewhere) that suggests I have lost the faculty of reason or cannot trust my perception of the world?

   I'll return to the subject of delusion in a moment, because I think this particular preconception that many people have interacts with actual gender dysphoria in a very nasty way sometimes. I have a lot of fears relating to this last point.

<p align="center">:::: :</p>

If these simple phrases don't describe my experience very well, what does? The best -- or perhaps "least bad" -- way to describe it that I can come up with is that for a long time I have had a sense of distress associated with my sexed body. What I mean by this is that I have always disliked having a penis, and I loathed all the changes that happened to my body during puberty. The process of developing male secondary sexual characteristics felt like body horror to me, and I didn't know why I felt that way. The underlying "signal" appears to be quite low-level, and not something to which I have direct conscious access.

Whatever the "thing" that drove my transition might be, it revealed itself only indirectly. Before I had even started transitioning, there were hints: my body felt less disgusting in situations where I was able to appear feminine. Anything I was able to do to counteract the perceived masculinity of my body made it a little easier to tolerate that body. I didn't perceive this as gender dysphoria at the time, nor did I see it as any hint that I might be transgender. Rather, I considered myself a feminine man who was a little too afraid and ashamed of what he was to let much of that femininity show. 

Even later in the process, when I was quite a long way along my transition trajectory, I still didn't have conscious access to my gender identity (which I guess is what we're talking about here?) I didn't have any sudden revelation "ah, I'm a woman!" and I still cannot fathom what that might even mean. Instead, what I experienced was a more intense version of the same signal I described above. The phenomenology of it -- to the extent I trust my own retrospective introspection -- felt more akin to a sense of "familiarity". When you see someone and you can't quite place them, but you know that you know them? It's that sensation. When I started transitioning, I felt a sense of "familiarity" with my own reflection that hadn't been there before. It came with a sense of relief as well: all my life there has been this low-grade sense of disgust I would have every time I saw myself that I had (not unreasonably!) attributed to my depression, which just ... vanished. The person I see in the reflection is more easily recognised as *me*.

If I didn't have conscious access to very much, I think it's worth asking how it was that I got here from there? To me it felt like an undirected exploratory process coupled with a very highly biased accept/reject decision at each point: every time I took a step in the direction of transitioning, of changing my body, my behaviour and my attire, I felt a sense of relief and comfort. It felt *genuine*. Any time I considered going back, I felt dread and disgust. It felt *wrong*. I made the choices that I made, not with the goal of transitioning to live as a woman -- whatever we take that expression to mean -- but rather with the more modest ambition "minimising my disgust and loathing for myself". 

I'm not entirely stupid, however, and it became painfully obvious after a while that I was headed in the direction of gender transition. I really did not want to transition, and tried awfully hard not to do it (just ask my therapist!), but -- strange as this sounds -- I didn't have much control over the process. It just sort of happened by osmosis: in real life it is almost impossible to stay perfectly still and change nothing about yourself, though I tried terribly hard to do precisely that. Every little step toward transition was a relief, a burden shed; every attempt to step the other way was so utterly aversive that I couldn't do it. 

And so here I am. 

<p align="center">:::: :</p>

One of the peculiarities of being a transgender woman and (trying to be) thoughtful about it is that I take a lot of care not to make stronger claims about my identity than are strictly necessary to make the points that I wish to make. For example, when I wrote my long post on [transgender rights](/post/an-ordinary-account) I took care not to base any of my assertions about trans rights on any metaphysical claim that I am a "real woman", because I don't believe that my rights are in any meaningful sense dependent on such a claim. 

Similarly, when I wrote [my post](/post/a-lexical-decision/) explaining why I refer to myself as a trans woman -- and sometimes simply as, gasp, a woman -- I was similarly careful not to make any particular claim about who is an who is not a "real woman". Speaking for myself I am unsure how to define the term "real woman" or be prescriptive about who counts as one, and so am careful not to rely on it when I discuss my life. 

Unfortunately, other people are not so circumspect, and their behaviour can cause me a lot of distress. Here are a few comments that have been written about me (personally, I mean, not trans women in general) on twitter in the last few days.

> you are definitely a guy ... you are a guy who for whatever reason thinks he's a girl ... it has to do with reality ... people are encouraging you ... people are telling you what you want to hear, not what you need to hear ... its REALITY ... if you can't grow out of those sorts of things, you'll never be an adult ... back in the day those people would be in mental care facilities

It is hard to overstate the magnitude of the psychological distress these comments cause. As bad as you (the presumed cisgender reader) might think these comments feel to me, in reality they are much, much worse. I'll try to explain why that is.

The starting point is to note that -- in my experience, thankfully -- there aren't many people who are willing to say these things directly to me. Not even on twitter. Most people are actually quite nice to me. However, there is quite a discrepancy between things that people say "to my face" and the things that I cannot avoid noticing being said "behind my back". There are a *lot* of people who say exactly this kind of thing  about transgender people -- especially trans women -- on twitter and on other websites. It is impossible not to notice this. When they aren't talking directly to me, there are a lot of extraordinarily horrible things some people will say about people like me. 

Although it is a small mercy that few people say such things to my face, it is something of a mixed blessing. The obnoxious things that people sometimes *do* say to me are so eerily similar to my worst fears, and so similar to the unpleasant things I see people saying in other places, that I start wondering. Maybe those comments are right:

> you are definitely a guy ... you are a guy who for whatever reason thinks he's a girl ... it has to do with reality ... people are encouraging you ... people are telling you what you want to hear, not what you need to hear ... its REALITY ... if you can't grow out of those sorts of things, you'll never be an adult ... back in the day those people would be in mental care facilities

This time around it's not *them* saying it, it's me. That's much worse. 

It's trivially easy to deal with one minor troll on twitter saying nasty things, and by now I've had quite a bit of practice in doing so. However, it's a lot harder when the source of the nasty words is not the twitter troll per se, but all my personal demons who tell me the same story. Unlike a troll, my fears are not easily muted. Perhaps my perception of myself and the world is irredeemably flawed. Perhaps everything I have written here and elsewhere is simply a comforting lie I have told myself. Maybe I *should* be in a mental care facility: can I really be trusted to exercise my own autonomy? Maybe ... maybe I truly am delusional?

<p align="center">::::: :</p>

I talked about this fear on twitter, and I'll expand on it here. 

My fear stems from having grown up in a world where it was accepted as "obvious truth" that people like me are inherently disordered and the simple fact of being transgender was prima facie evidence of delusion. We could never be trusted to be rational. This worldview has changed, but only recently. Even 10 years ago it was still widely accepted that being transgender *is* a mental illness. That world view is still very common, and it is still in my head just as much as everyone else of my generation. 

When a random troll appears on twitter or [elsewhere](https://statmodeling.stat.columbia.edu/2020/07/21/male-bisexuality-gets-big-pnas-energy/#comment-1389837) to make some silly and childish remark about trans people being mentally ill, or when I see academics writing articles, posts and tweets that dispute or deliberately undermine the validity of transgender identities -- recent examples [here](https://twitter.com/SwipeWright/status/1293326796713160704), [here](https://twitter.com/normfinkelstein/status/1292842046387101696), [here](https://www.theaustralian.com.au/inquirer/few-female-engineers-its-a-matter-of-choice/news-story/5c9a4d58ddf7656a0920d597d413339b) and [here](https://medium.com/@aytchellis/trans-men-are-men-but-transwomen-are-not-women-7ba7a533e8a5), but honestly these things are a constant stream and these examples are neither remarkable or unusual -- it has a larger effect on me than merely "hurting my feelings". It makes me question my sanity.

Because I am trans, these things are sent to me by friends, colleagues, etc and I necessarily get dragged into things I'd prefer not to. Worse yet, because I am a trans *woman*, almost all of these things target people like me specifically. The vast majority of anti-trans sentiment is directed at trans women, and being the target of this that has a severely negative effect on my mental health. As an example, I've just spent three weeks arguing patiently with a colleague -- trying my best to hold back my own fear -- that some of the things he's written about us in national newspapers are unkind (it was a follow up to [this post](/post/on-small-differences/)). I think I convinced him in the end, but I won't lie, it came at a dreadful personal cost. 

Not by choice then, my everyday environment is one in which I am constantly exposed to material that mocks me, humiliates me and asserts that I am delusional; and every day I remember what the world used to be like and the world view I was raised with. I see a world in which my very sanity is considered a debatable subject. But everyone around me don't have the same exposure to this kind of content, and they don't carry around the same fears and insecurities that I do.

So what happens is this cycle. I see something that causes distress and I try to ask for help (sometimes on Twitter). Other people don't see any of the surrounding history or context and they shrug it off and say "just ignore it -- they're just trolls". This throws me for a loop. From my perspective I am struggling to believe that I am sane, that I am not delusional simply because I am transgender. I ask people for help and everyone seems ... indifferent to the level of terror I feel. 

So what should I make of all this? Is it me (one person) misreading the world or is is it you (many, many people)? Ockham's razor suggests it is me. That I am wrong, that I am unable to correctly perceive the state of the world ... in other words, that I am delusional. From that point it spirals. I have no reference point to determine whether my own reason is trustworthy and every signal I am getting from my friends, my family, my peers suggests that I am in fact, delusional. In short there is a mechanism by with other people's silence (which to me is quite conspicuous) reinforces my fear that I should not trust my own perception of the world. As a result, the patterns of interaction that I end up in due to this can (and do) cause me a lot of harm, and severely impair my mental health.

<p align="center">::::: :</p>

At long last I approach the real point of this post. For four years I have tried to convince my academic colleagues that supporting transgender people means something more than mumbling a few nice words, tweeting the occasional news article, and then going back to writing grant applications. For four years I have failed at this. 

For a while I thought that the problem was simply a lack of understanding. Perhaps, I told myself, that my colleagues and peers simply did not understand what life is like for trans women. Perhaps this lack of understanding is the reason why it has been almost impossible to convince them to take action. So I have written [post](https://djnavarro.net/post/in-between) [after](/post/52-pickup/) [post](/post/an-ordinary-account/) [after](/post/never-the-same/) [post](/post/on-small-differences/) [after post](/post/a-lexical-decision/) on this blog. I have engaged on twitter, on other academic blogs, and other professional forums. I have participated in ally training at universities, agreed to be a speaker at workshops, and so on. None of it has made a dent in the wall of apparent indifference that I encounter whenever the next thing happens. 

Every time the story is the same. I literally beg people -- academics with immaculate progressive credentials -- for their support, and they remain silent. Transgender rights, and especially trans women's rights, have become a political battleground. Yet within academia only one side is really fighting. Conservative academics are only too willing to opine about my life. The progressives, however, are simply milling around, standing off to the side and assuming that somehow "the right side of history" will prevail without them having to lift a finger.

And so I think the time has come for me to give up. 

<p align="center">::::: :</p>

Trans women have become a [symbol](https://twitter.com/tage_rai/status/1292679700704264193) in the culture wars, our rights and our lives treated as a debate topic and little else. This is dispiriting. On the one hand, I try to take some solace in the fact that very little of this "debate" has anything to do with us at all -- we have become, rather, a proxy for arguments over "cancel culture", "social justice warriors" and "the woke". On the other hand, I am reminded of Kate Manne's grim phrasing in *Down Girl: The Logic of Misogyny*:

> When one's effigy is one's body, one burns right along with it 

Even if this humiliating public debate is merely a "culture war", the crossfire that we are caught up in is very real to us. With all due respect to the political sensibilities of cisgender people -- and in frankness, none is warranted -- I would like to remove myself from your battleground.

My life as an unwilling participant in the culture war has worn me down. A few days ago I had to spend the night at the emergency room because the possibility of self harm had become quite serious, and in a way, that's actually form of progress on my part: in the past, I'd have tried to "tough it out" and most likely ended up actually hurting myself. Recognising the need to seek help and in doing so preventing any self-harm from happening is a genuine step forward. 

Which brings me to my real point: I don't want to talk about transgender lives and transgender rights anymore. Not on this blog. Not on twitter. Not at a university "diversity" event. I don't want to be your symbol, I don't want to be your diversity shield. I don't want to be the subject of your ridiculous culture war. It is degrading, and I hold both sides in contempt for their unwillingness to take our lives seriously. It does transgender people real harm to be treated in this way, and while I can do nothing to prevent you from continuing in this fashion, I do have some agency left. 

I can -- and with any luck, will -- withdraw my participation.

<p align="center">::::: :</p>

An epilogue. 

A few days ago, in an email exchange with a lovely cisgender colleague, he wrote this about his first experience attempting to engage with the anti-trans people:

> it's been completely enlightening about the things I had seen you and others discuss online, but I hadn't ever experienced. Thank you for suggesting that other people engage more -- I wish I had done it sooner ... I'm very happy there are people like you around with loud voices.

As wonderful as this sentiment is -- indeed, I cannot express how grateful I am for it -- I don't think I can continue speaking up the way I have done in the past. My mental health is fragile, and it is precious to me. It has become clear to me that the price for speaking with a loud voice is my health. 

This is a price that I am no longer willing to pay.

