---
title: On small effects
author: Danielle Navarro
date: '2020-07-12'
slug: on-small-effects
summary: "A brief comment on the importance of keeping things in perspective."
type: post
---

There is a strange kind of intellectual panic that academics are vulnerable to, whenever the subject of transgender women comes up. People who might under normal circumstances speak in a careful and measured fashion suddenly become prone to wild exaggeration and reckless generalisations. I am genuinely baffled as to why this happens. 

An email appeared in my work inbox this afternoon, forwarding [an article](https://www.theaustralian.com.au/inquirer/few-female-engineers-its-a-matter-of-choice/news-story/5c9a4d58ddf7656a0920d597d413339b) published in *The Australian* newspaper. The authors are academics and they self-identify as Madeleine Beekman, a "professor of evolutionary biology at the University of Sydney", and Bill von Hippel, a "professor of evolutionary psychology at the University of Queensland". The article begins with this passage:

> The Australian Academy of Sciences recently changed its definition of a woman. According to the new definition, anyone who identifies as a woman is a woman, regardless of their biological sex.

What this passage is referring to is the fact that AAS recently announced a policy of classifying transgender women such as myself as women for a variety of administrative, rather than as men as we would traditionally have been treated. It goes on to acknowledge that gosh maybe this is a good thing to do:

>This definition has the clear advantage that people who don’t identify with their biological sex will now be recognised as their preferred gender, an obvious social justice issue.

How nice. The very next sentence, however, is this:

>However, with this new definition of woman, the academy is tacitly stating that biological sex is of no significance. 

The article then pivots away from transgender women entirely. The vast majority of the piece has *nothing at all* to do with transgender people. Instead it focuses on whether there are meaningful biological sex differences between cisgender men and women that might explain the observed gender disparities in STEM disciplines. 

Oooookay. As a scientist as well as a transgender woman, I confess that I am puzzled (and more than a little annoyed) by that last sentence. Allow me to repeat it with emphasis:

> However, with this new definition of woman, the academy is tacitly stating that **biological sex is of no significance**. 

This is patently absurd, and if I hadn't seen this kind of ridiculous exaggeration from academics so very many times before I would be surprised that otherwise-intelligent people would make this error. When I point out that this is an utterly unreasonable thing to say, I am met with a kind of blank surprise and defensiveness so complete that I don't know how to address it. Cisgender academics appear to be genuinely shocked that I would say this. They literally cannot understand what that sentence is a nonsense.

So I suppose I had best explain why it is a nonsense. I wish I did not have to. I tire of having to point out things that should be obvious to even a casual observer, but evidently this has become my lot. 

<p align="center">::::</p>

Let us start at the beginning. 

Suppose for the moment that AAS had not adopted a trans-inclusive definition. Suppose they had decided to exclude transgender women, and treat "woman" as a purely biological category. As scientists perhaps they might have chosen to define "woman" in chromosomal terms: people with XX chromosomes are deemed women for administrative purposes and people with XY chromosomes are deemed men. This definition mostly (but not completely) agrees with our everyday concept of "men and women". Biology -- like any complex system -- is somewhat messy, and a small proportion of the populace are intersex, and not easy to classify under a simple definition. 

Overall though you'd be mostly accurate. There aren't very many intersex people (about 1-2% of the population), so your classification system would maybe be about 98% accurate. In most classification contexts we'd probably be happy to classify anything with that kind of success rate, but because we recognise that the rights of intersex persons are important (assuming we are not jerks), we aim to be flexible and allow intersex people to be treated as members of whichever category they feel most appropriate. It is very rare -- unheard of, in fact -- for academics who believe in biological sex categories to start wringing their hands and  boldly proclaim that the words "man" and "woman" have fundamentally changed their definition merely because intersex people exist and are given reasonable accommodations. 

Why, that would be *absurd*.

The existence of and recognition of a tiny minority does not suddenly render the cateogies "of no significance", now does it? Only a shallow and overly rigid thinker would make such a silly error.

<p align="center">::::</p>

Dear reader, you are not foolish and I know that you can see where I'm going with this, but please bear with me as I do so.

<p align="center">::::</p>

Suppose we now consider what happens when we adopt a trans-inclusive definition of gender categories, as the AAS has done. Transgender people are also a very small minority. Estimates vary, but 1% is probably a reasonable number. Even with the recent destigmatisation of transgender people, very few people who were assigned male at birth will choose to live as a woman. Very few people assigned female at birth choose to live as a man. Some people choose to reject both categories and identify as nonbinary, but again their numbers are few. 

In other words, by adopting a trans-inclusive definition, the accuracy of our chromosome based classifier might decrease from 98% to 97%. If biological (chromosomal) sex was deemed "essential" when it was 98%, why is it suddenly "of no significance" when we adopt a definition that shrinks the accuracy to 97%. 

Why, that would be *absurd*.

When framed in terms of the empirical base rates of intersex and transgender people, the scientific illiteracy of Beekman and von Hippel's claim is painfully clear. From a "cold hard facts" perspective it makes no sense whatsoever to assert one definition ignores the reality of biological sex and the other does not. When the practical differences between the two approaches are so tiny, it simply can't be so. I think it is of some interest to consider why smart people would make such a foolish mistake.

<p align="center">::::</p>

I have a personal theory as to why this happens, one that I've never tested nor found any good way to test. It's quite a simple theory, actually: *cisgender people rarely think about how transgender lives work*.

The idea goes like this. To every transgender person it is painfully obvious that being transgender is a massive disadvantage in life. I regularly receive abusive comments on social media, have been threatened with violence, and live in constant fear that my basic rights will be taken away from me for no reason other than naked partisan gain by cynical politicians. When I that say I "identify as a woman", I don't just mean that on a whim I decided to throw on a dress one day. In point of fact I don't wear makeup and I rarely wear dresses: I'm a jeans and black t-shirts girl myself. What I mean is that over the last four years I have:

- Been diagnosed with gender dysphoria
- Taken hormone replacement therapy and as a consequence
- Grown breasts
- Had my facial hair removed in an extremely painful way
- Changed my name legally
- Changed id document after id document
- Learned a whole new set of tiresome social rules
- Et cetera et cetera.

The point is that under no realistic definition of "gender identification" is this a small thing (I've talked about this [before](/post/an-ordinary-account/)). Gender transition is long, painful and filled with many traps for the unwary. When one takes the time to think it through it comes as no surprise to discover that so few people actually undertake it, especially when one considers the fact that most people have no desire to transition either.

In other words, the idea that something like the AAS policy could lead to a free for all on gender doesn't hold up under even a moment's examination when it is evaluated against the reality of our lives. Unfortunately, because cisgender people don't even *think* about us and our lives, it never occurs to them to go through this reasoning process, and they end up making very silly claims as a consequence. 

<p align="center">::::</p>

There's a second reason I think things like this happens, and why this particular fallacy is so common among academics: pedantry. In one instance the definition *explicitly* links gender categories to biological sex (leading to the 98% classification accuracy of sex as a predictor of gender), and in the other instance the definition only *implicitly* ties gender to sex (leading to the 97% classification accuracy). If we lived in a different world, one where the base rates were completely at odds with our own and 40% of the populace was trans, then there would be a practical difference between the two definitions. 

In that world, the inference that Beekman and von Hippel made would have been quite sensible. However, we don't live in that world. Transgender people are a very tiny minority, and it is an act of pure pedantry to insist that biological sex has been deemed "of no significance" in *this* world solely because we can imagine a counterfactual world in which the two definitions would behave differently in practice. 

More than mere pedantry, it is cruel. To decide that this is the hill one wishes to die upon is to say that -- as far as you are concerned -- the reality of actual transgender lives is of less importance than a trite debating point. 

And so I have ended up with something of a contradiction. At the very beginning of their article Beekman and von Hippel imply that it is a good thing for social justice purposes that transgender people are accorded some status in society and by the AAS. Yet if we are to take their claims about the AAS definition at face value, we are led to a rather different conclusion. 

The truth is that I don't know what's going on here. I cannot tell if their claim to support transgender people is a lie, if they didn't think their claim through, or if they simply didn't intend that part of their article to be taken too literally. Perhaps they just meant it to be a "rhetorical flourish".

The thing is, I don't care. I have no desire to be your rhetorical device or your debating point. It is degrading and humiliating to be treated so by my academic colleagues, but it is depressingly common. 
