---
title: Never the same girl twice
author: Danielle Navarro
date: '2020-05-31'
slug: never-the-same
summary: "I am haunted by a pedestrian phrase. \"You're still the same person\", I am told. It is a phrase offered with kindness, as a reassurance of sorts, usually on those occasions when the subject of my gender transition arises. It's an expression of support. How you appear to the outside world may have changed, my interlocutor concedes, but on the inside you're still the same person I've always known and liked all these years. The unspoken implication hangs in the air: things will remain the same. [DRAFT POST]"
type: post
---

I am haunted by a  pedestrian phrase. *"You're still the same person"*, I am told. It is a phrase offered with kindness, as a reassurance of sorts, usually on those occasions when the subject of my gender transition arises. It's an expression of support. How you appear to the outside world may have changed, my interlocutor concedes, but on the inside you're still the same person I've always known and liked all these years. The unspoken implication hangs in the air: things will remain the same.

They won't though. Everything changes.

> I found the dates in my calendar. November 26th 2018 was the day when I a lawyer at the Inner City Legal Centre helped me put together the paperwork for my application to update the gender marker on my birth certificate. I'd been out for maybe a year? It's hard to give a precise date for "coming out", but if forced to pick I'd have to choose the work Christmas party on 20th December 2017. I started hormones on 10th April 2018. The birth certificate was issued on 12th December 2018. Since that point I have been a "recognised transgender person" and for the first time was entitled to some degree of protection under the law.

Some changes are easier to handle than others. My name was Daniel and now it is Danielle. Daniel wore blue jeans and black t-shirts. Danielle wears blue jeans and black t-shirts too, albeit with nicer boots than he ever owned. Daniel was "he", Danielle is "she". He had a facil hair, she has breasts. People experience some cognitive dissonance about it, but less than I thought they would. It takes time for the weirdness to fade away, but fade it most certainly does. 
The hardest thing to accept, that people fight so hard not to notice, is the fact that I'm not the same person anymore. Oh everybody changes all the time, they'll say breezily, as though I'd admitted that I don't like pizza anymore. Yet again the implication hangs unspoken in the air: at a fundamental level you are still him and I don't have to change my mental representation of you. Please don't make me meet the new woman. I liked him -- what if I don't like her? What if she doesn't like me? You're still *mostly* the same as him right? To me it feels like they're negotiating, bargaining to see how much of Daniel they can keep.   

> Today is May 31st, 2020. It's been a strange year so far. Early in the year massive bushfires engulfed large parts of New South Wales and Victoria, on a scale I've never seen in my life. At one point there were eight separate fires burning that were individually bigger than the largest bushfire in US history. We were barely recovering from that catstrophe when the global coronavirus pandemic hit. At this point it has infected 6 million people worldwide and killed 370,000. Perhaps by luck, perhaps by good planning and response Australia has been spared the worst of it, with just over 7000 cases and 103 deaths so far. Even here the borders are all closed, we have had strict nationwide lockdowns since mid-March. Restrictions are very slowly being eased, but authorities are rightly wary. 



The bargaining doesn't really work. Yes, often I would try to accommodate. I can work on Daniel's research projects, I can teach his classes, I can do a lot of things other people needed him to do. But I'm not invested in them the same way he was. Danielle, it turns out, has her own ideas about what matters in life, and first passage time density computations for Weiner diffusion processes are not numbered among them. And so eventually the time comes when I can't be the person they want. Daniel was not an indolent man, and as competent as Danielle is, she's not so good at what she does that she can do his job as well as her own. My boundaries are different to his. When I start to assert them it comes as a shock, and people I care about get incredibly angry at me. 

It surprised me, but maybe it shouldn't. Every time I do things that he would not have done -- or worse, don't do something he would have -- it seems to force people to realise the thing that has been staring them in the face the whole time. Daniel is gone and he's been gone a long time. I didn't even grasp it myself initially. For the first couple of years as Danielle I tried to hold onto many things I used to care about. It was my way of clinging to the man whose life I've inherited, as though his memories could ward off the misery over what -- who -- I'd lost. I ought not be surprised that other people do the same. 

It is, I have come to realise, a kind of grief.

> I'm lying in bed doomscrolling on twitter. Right now there are riots taking place across dozens of cities in the United States sparked by the murder of George Floyd by a police officer in Minneapolis. Yet despite the protests internationally, it is very peaceful here in Sydney's inner west. A quiet Sunday afternoon in Newtown. 
>
> My thoughts have returned to November 26 2018. Sitting on a bench on Darlinghurst road. Waiting anxiously for my appointment with the lawyer, reading the plaques embedded in the footpath commemorating the place that Kings Cross has played in LGBTIQ history and as the traditional red light district in Sydney. My thoughts have returned to January 25 2020, walking through the Compton Transgender District in the Tenderloin in San Francisco, reading the plaques in the sidewalk commemorating the Compton's Cafeteria Riot in 1966, the first major LGBTIQ riot in United States history. Walking through the Tenderloin as a white middle class Australian is a reminder of how stark the inequalities and injustices in American society are. Right next to the fancy hotel I was staying in for my fancy tech conference I was being paid to attend is a tent city where a large homeless population lives. It goes without saying that very few of the homeless in the Tenderloin are white. 


People who have only ever known me as Danielle don't go through this. To them, "Daniel" is an abstract concept. Of course he must have existed. How else could Danielle be the person she is now, if not for him? But that's just an abstraction. They didn't really know him. At an emotional level, I have always been Danielle to them. There is no sense of loss. My transition never caused them to lose someone they liked, someone they loved.

I wish I could say this story has a happy ending, but I don't know if it does. In transition I've lost a lot of friends, often very dear ones, not through prejudice or intolerance, but through grief. His friends sometimes find me discomforting; I feel the same about them. We fall back on old habits, and for a moment or two it is just like old times. 

It makes it harder to accept our shared loss.










