---
output: hugodown::md_document
title: Meaningless questions do not have meaningful answers
author: Danielle Navarro
date: '2020-08-21'
slug: trans-women-are
summary: "I don't have an opinion about whether trans women are real women, any more than I have an estimate of the number of angels that can dance on the head of a pin or a belief about the mood of Thursday."
type: post
---

It is probably not difficult to infer that I dislike the phrase "trans women are women". In my post on [transgender rights](/post/an-ordinary-account), I took care to outline my opinions in a way that makes no reference to *any* claim about whether I am a "real woman". I have been consistent on this point for a long time: I do not think that the case for transgender rights rests on any such claim, so I do not and will not include it in any argument I make regarding the rights of transgender people.

Similarly when I wrote my post on why I [describe myself as a trans woman](/post/a-lexical-decision) and at times simply as a woman, I did not justify myself by making any claim about being a "real" woman. Even if my gender identity were a total fiction, in most cases we don't usually have a problem with calling fictional women "women" even though we would agree they are not real women. My willingness to use the word is not dependent on any strong metaphysical stance. You get the idea.

Nevertheless people do sometimes ask or expect me to take a position on this question. It irritates me: people ask me this question expecting that I will have a yes or no answer for them. I don't have one. I think it's an absurd and ambiguous question, and I can't give you a proper answer to it unless you are more precise about what you are asking me. There are lots of ways that you can make it more precise, and my answer is different in each case. With this in mind, the following brief Q&A attempts to summarise my thoughts.

<p align="center">::::::</p>

-   Do you think trans women should be treated as women? 
    
    > As a default, yes. My reasoning for this is outlined [here](/post/an-ordinary-account) and [here](/post/a-lexical-decision)
    

-   Do you think there are situations where that default might not apply or not be appropriate?

    > Yes. Though it is often maligned, I am a firm believer in the practical value of [casuistry](https://en.wikipedia.org/wiki/Casuistry). The specific rules and norms that are called for in any particular situation will tend to vary. Different scenarios require different approaches


-   Do you believe that a transgender woman is biologically female in the same sense that a cisgender woman is biologically female?

    > No


-   Do you believe facts about sex and reproductive biology should be considered relevant to discussions about gender? 

    > Yes

-   Do you believe facts about sex and reproductive biology are the *only* facts relevant to discussions about gender?

    > No
    
-   Do you believe that "being a woman" is a psychological state, solely a function of a person's feelings and sense of personal identity? 

    > No. Laws, cultural norms and biology matter, and are relevant to the question

-   Are trans women are biologically male? (Stipulate good faith)

    > In some cases yes. In others, not necessarily. The biological sex characteristics for a transsexual woman such as myself are an odd mixture. For example, I (probably) have XY chromosomes, but I also have high oestrogen levels, near zero testosterone, and I have breasts. These are all aspects of biological sex in humans, and that does matter. If you are discussing this subject in good faith you are not entitled to cherry pick the data: you cannot choose which sex characteristics are "legitimately" relevant to female sex solely for the purposes of excluding transsexual women from consideration. It is intellectually dishonest to do so

-   Are trans women biologically male? (Pretend this is twitter)

    > I think this question is a trap. In almost every case when I have seen this question asked in real life, it is a prelude to a rhetorical pivot. The moment the respondent agrees to the biological claim, the speaker takes this as a justification to no longer use the term "trans women" in any context, and thereafter refers to trans women exclusively as "biological males". In other words it is the "motte" part of a [motte and bailey fallacy](https://en.wikipedia.org/wiki/Motte-and-bailey_fallacy) that is used to defend misgendering, to deny trans women the right to our pronouns, and more generally to justify cruelty to trans people. I have learned from bitter experience not to trust anyone who asks me this question, because is almost never asked in good faith

-   What about the term "natal male"? Are trans women natal males?

    > Yes. The term "natal males" refers to the sex registered at birth: it refers to an administrative classification that is tied to biological sex. My original birth certificate listed me as male, so I am by definition a natal male

-   So it's okay to call trans women natal males?

    > No, absolutely not
    >
    > In almost every context the appropriate term to refer to us is simply "trans woman". As I mentioned earlier, the use of terms like "natal male" and "biological male" in everyday language is not neutral: rather it is a rhetorical way to avoid having to call us women. It is misgendering, pure and simple. The legitimate use case for the term "natal male" is pretty narrow, and is mostly restricted to situations when precision is needed in administrative or scientific contexts. Outside those contexts, it's completely inappropriate language

-   Do you support other trans women in the political fight for civil rights? 

    > Yes. Trans rights are human rights. Discussions about trans people in the public sphere are fundamentally political discussions. The questions that matter are those pertaining to the civil rights of transgender people. This is not an academic debate about sex and gender, and to construe it as such is to miss the point entirely


-   Are you a transmedicalist?

    > No. Absolutely not. The transmedicalist position is much stronger than simply acknowledging nuances about biology. Rather, it is a political position in which some transsexual people do not acknowledge the legitimacy of other members of the trans and gender diverse community. As a political stance I will not have any part of it and I repudiate it entirely


-   Do you believe trans women are "real women" in a metaphysical sense? 

    > Good grief, what possible reason could I have to cares about metaphysics? I don't know the answer to the question and I regard it as a waste of my time to try to figure it out. In the real world I am far more concerned about violence and hatred directed at trans people, about the homelessness and unemployment risk we face, and other subjects that actually matter. Come back to me when I have spare time to waste on pointless questions

<p align="center">::::::</p>

It does not matter whether "trans women are real women". It is sufficient merely to note that "trans women are", and we deserve to be treated with kindness and respect simply by virtue of being human beings. The public debate about what we "really" are is fundamentally disrespectful and there isn't any hope of a resolution because the question as stated is meaningless and underspecified. Per the title of the post, *meaningless questions do not have meaningful answers*, and this one is about as meaningless as it gets
