---
title: An ordinary account
author: Danielle Navarro
date: '2019-10-24'
slug: an-ordinary-account
type: post
summary: "A long piece on transgender rights, in which I admit that I do have opinions on what social and political considerations a person such as myself deserves. The central claim is that transgender rights can be justified on their own terms, pragmatically, without requiring any recourse to strong metaphysical claims about the nature of gender identity."
---

From time to time I encounter people wanting me to become an activist, and advocate for transgender rights or to engage in academic discussions about the subject. I think that's a bad idea. I don't have the temperament to make a good activist, and I don't take kindly to the way academics like to discuss or study us as intellectual curiosities. On the whole I find it humiliating and I prefer not to participate. 

That being said, I am so often frustrated by the way in which these discussions unfold that against my better judgement I get drawn into the fray. With that in mind, for the sake of trying to get this out of my own head and onto paper (metaphorically speaking...) I'll try to say something about my own perspective on transgender rights. As much as anyone else I ought to be entitled to an opinion, right?

## Assumptions and caveats

Before getting into the particulars, I think it is useful to say something about the intended scope and (hypothetical) audience for the post. To start with, the *focus* of the post is on the kinds of issues that typically arise in the public debate around transgender people. However, there are some caveats here:

- I'm not going to talk about the psychology of being transgender. There are reasons for this, not least of which is the fact that I am a mathematical psychologist and I have some professional opinions on the methodological practices in the associated literature that -- for now at least -- I'd prefer to think about before commenting on publicly. That is, while I do have opinions about topics such as Blanchard's typology of transsexualism, these topics are sufficiently close to my area of professional expertise that I do not want to discuss them here. *If* I ever decide to speak publicly to those topics, it will be with my professional voice and not merely that of being a member of the affected population, so I'm going to remain silent on this one for the present.

- I'm not going to talk about transgender children, persistence of gender dysphoria in kids, or any of the issues surrounding that topic. That's another area where I don't have very coherent opinions at this point in time. I have only read small sections of the literature, and would prefer not to comment until I have something considered to say.

- I'm not going to talk very much about trans men, nonbinary people, intersex folks or detransitioners. I'm not personally a member of any of those categories and I don't think I am the best person to speak to their experiences; all I wish to assert here regarding those groups is that their interests *matter*, and all of these groups tend to be overlooked due to the relentless focus on trans women and trans kids in the public debate. I find it incredibly annoying. I think we'd have a much better discussion on LGBTIQ issues more generally if as a society we spent more time listening to those folks too. Most importantly, it would be great if we could stop using these groups of people as "mere vehicles" to assert an opinion (pro- or anti-) about trans women. It's disrespectful.

Next up, some *assumptions* that I am making here:

- The biggest assumption I'm making is that I have good faith reader. Often, when writing on a contentious topic, it is possible to misstate or misphrase things in a way that allows a malicious reader to twist the text so that it appears to say something other than what it actually does. This is very common in academia, to the point where academic writing is so often stilted and awkward *because* the author is trying to write "defensively", guarding against attacks from a malicious reader. In this piece I'm not trying to write an airtight argument that covers every possible scenario, so much as sketch out a set of opinions and the core of an explanation for why I hold them.

- I am assuming that the reader would concede that transgender people (including trans women) deserve legal protections in our own right -- e.g., we deserve to constitute what in US law would be called a protected class -- purely by virtue of the way we are treated in society. One critical entailment of this assumption is that I think trans women deserve legal protections *because we are trans women*, as an entirely separate matter from whether we are "real" women.^[In fact, I'm going to avoid making any specific claim about whether I am a "real woman" at all. Perhaps surprisingly, I don't think that's an interesting or an important question.] 

  In my opinion the fact that transgender people require some form of legal protection is so obvious that it should not even need to be argued: the [statistics](http://www.ustranssurvey.org/) regarding health, homelessness, sexual assault, unemployment, abuse, discrimination etc, issues that are faced by the transgender population are sufficiently grim that I expect that this would be taken as a given by any good faith reader. If a person is not to willing to concede that much, I think I can reasonably conclude they are not engaging in good faith and are not the intended audience of this post.

- I'm assuming that transgender people are one among several groups that need legal protection (e.g., cisgender women, everyone else in the LGBTIQ coalition, people of colour etc); and I am also assuming that we operate in a world in which some proportion of the population are predatory: e.g., part of what we're all trying to seek protection from is male violence. It is a sad truth that this is our world, but it is.

Okay, with that out of the way, I should probably start...

## When is self-identification sufficient to establish gender?

Before diving into thinking about contentious topics, I want to start by pointing out the obvious: most people in most situations simply don't have a problem with self-identification. In practice it genuinely is considered legitimate for me to say "I'm a woman" and have that accepted on my say-so, without any other verification process. This might sound surprising, but in practice lot of social and bureaucratic interaction falls in this category. I sign my emails "Danielle" and tick the box marked "F" when enrolling in a class, I use "she" and "her" when talking about myself in the third person, and... nothing happens. Nobody cares, nobody argues. It's not *interesting* enough for anyone to bother. 

Most of the time I don't even need to say anything or make any explicit claim. When I sit down at a restaurant and the staff member asks "what can I get you ma'am?" I haven't provided any documentation, I haven't made any verbal claim, but I *have* provided a form of self-identification by virtue of my appearance. I don't have facial hair, I do have breasts, my clothing is somewhat feminine, etc. It's hard for me to judge honestly, but from what other people tell me I'm usually presumed to be a cisgender woman when people first meet me. Not always of course: some people do notice, but it's a lot less common than I thought it would be when I started transitioning. Nevertheless, even when people do clock me as trans, they still (usually) accept the implied self-identification and generally call me "she" etc. When they do this they aren't asserting *"why yes Danielle you are a real woman and identical to a cis woman in every respect"*, not by any stretch of the imagination. Rather they're just being polite to me -- and that's kind of the point here! Most of the time, people do accept each other's self-identified gender because it's just not that big a deal. Unless you are trying to be a jerk, it is just everyday good manners to accept a person's self-identified gender in most scenarios.

Of course -- as the philosophers tell me at tedious length -- one cannot derive an "ought" from an "is". Just because people are polite most of the time doesn't necessarily mean this politeness is a good idea.  Logically, it could very well be the case that this everyday social practice is immoral or unethical, but frankly I think that in this instance it's an absurdity to suggest it. Everyone just wants to be able to go about their lives without unnecessary hassle. It's a mere politeness, nothing more, and no less than anyone else I'd like to think I deserve common courtesy.

## Why do transgender people need legal recognition?

I've argued above that in most everyday situations, "self-identification" of one's gender is innocuous, sufficient, and in fact *is* accepted by most people unless they are deliberately being a jerk. However, that doesn't mean we should accept self-identification in every context. In public debate, the most prominent example of this regards *legal recognition*. What criterion should be required for the law to recognise a transgender person as a transgender person? What does this "recognition" entail anyway?

To put my cards on the table at the outset, I think legal documentation is a situation where "pure" self-identification is unwise. If I want my drivers licence, passport, etc, to show my gender marker as "female" rather than "male" I don't think it's quite enough for me simply to say "I am a woman" with no mechanism *at all* by which this self-identification could be queried. I'll explain why I think this in a moment, but I also want to point out that *none* the legislative regimes currently in place (or proposed) in Australia are that lax (i.e., the legislation that is commonly referred to as "self ID" isn't actually a pure self-identification system at all). But I'm getting ahead of myself, because there's another question I think I need to address first... why do transgender people want legal recognition at all?^[As an aside, I ought not to have to say this, but there is a massive difference between *allowing* transgender people access to documentation and *requiring* us to carry [identification documents](https://www.telegraph.co.uk/women/life/gender-neutral-bathrooms-womens-prisons-time-trans-people-carried/) at all times. The former allows us to have the same freedoms as anyone else within a highly bureaucratic society, the latter is a form of mandatory surveillance and authoritarianism. I should also say that because the linked article is paywalled, I've only read summaries of it but I don't hold out a lot of hope that the piece is anything other than what it sounds like. Curiously, the article is written by a transgender person (a trans man, I think?) but -- as I have discovered -- transgender people can hold some pretty awful views about transgender rights sometimes.]

One of the stranger things I've noticed when following the discussions is that a lot of cisgender people have some really strange views about why transgender people want legal documentation. Specifically, the claim is sometimes that we want legal documentation for our own personal validation. This is of course an absurdity.^[Actually, I suspect it's just an outright lie. Any honest participant in the discussion knows perfectly well that this isn't the real reason transgender people care so much about legal documentation, and the attempt to mischaracterise our position is, I suspect, a deliberate deception.] That warm and fuzzy feeling I get at seeing the "F" on my passport is nice, but isn't a serious justification for a legal process. On the contrary, the reasons that we care so much about documentation are safety and accessibility.

An illustrative example. When I cross borders, I need to go through customs and I need a passport. In this situation the last thing I want is a passport that says "M" on it. Looking the way I do, I can absolutely guarantee you that I will be subject to all sorts of invasive scrutiny if I hand over a man's passport^[Depressingly, in the United Stated, thanks to the invasive TSA procedures, even having good documentation isn't any guarantee at all; as every trans woman who has gone through a TSA checkpoint can attest. Fortunately, in other places it actually does work. When I fly domestically in Australia, or go through customs at any country that doesn't have de facto mandatory genital "patdowns" for transgender people, it's totally fine now that I have papers.]. Sadly, I speak from experience here. 

Less dramatically, it is a fact that we live in a bureaucratic society. We so often need to show identification documents of some kind, and if you don't have these documents (or if your documentation looks "strange" to the person inspecting them) you can be subject to all kinds of unnecessary and occasionally upsetting scrutiny. I've now reached the point that *most* of my documentation has my name listed as "Danielle" and my gender listed as "female"^[Honestly I don't know why legal documents insist on showing sex/gender, but a lot of them do.] and I'm starting to relax a bit, but for a long time I lived with a constant fear of suddenly being "outed" to strangers *by my own documentation*. Thankfully these "omg, you're a tranny!?" moments have never led to anything worse than the occasional insult or sneer in my case,^[Oddly enough, trans women of colour have told me that these kinds of documentation-enforced reveals of their transgender status tend to be much less benign for them, particularly if they are not Australian citizens. While my experiences have been comparatively mild, not everyone is so lucky.] but it is pretty tiresome to be publicly humiliated on a regular basis. 

So okay, let's assume that one accepts that transgender people deserve access to some legal recognition and that this should be reflected in legal documentation in some fashion. Why should that documentation process entail changing a  *birth certificate* specifically? After all, it's not often that anyone ever needs to see a birth certificate, right? The answer to this was explained to me by the lawyer who helped me through the process: in our legal system the birth certificate is the primary document for establishing gender/sex, and everything else flows from that. One way or another, every other substantive legal document that makes a claim about sex/gender depends on the birth certificate *unless there is a specific exemption* process made available to transgender people. So if you concede that transgender people need government identification that recognises us, noting it on the birth certificate is actually the easiest way to do that. As a purely practical matter, it's far, far simpler to issue a new birth certificate than to create "special" procedures for transgender people in every other administrative system. Unless you have a deep and abiding love of red tape, reissuing birth certificates is the simplest, most practical solution.

As a final note, it's worth saying something about what actually happens when you change your birth certificate. I've noticed that the public debate about the topic often reveals a very shallow grasp of what it means to change the sex/gender marker on your birth certificate, so perhaps it is useful to expand on this. In Australia, birth certificates are handled at the State level -- I was born in South Australia, so it is the South Australian law that applies to me even though I live in Sydney.^[Blah blah jurisdictional cross-vesting blah blah blah.] When I changed my gender marker, the government reissued my birth certificate in *two* forms, both of which are considered legally acceptable throughout Australia. Both versions list my sex/gender identity as "female", but only one of them states explicitly that a "male to female" transition has been registered and only this version lists my original name. This duplication is a deliberate choice by the South Australian government: in situations where I do not wish to be outed as transgender I can show the version that doesn't include the extra detail and hence retain some semblance of privacy, whereas in situations where I need to assert continuity with my old identity, I can show the version that does. This is a nice touch, and something I deeply appreciate.

This brings me to a really important point about the reissued birth certificates ... these alterations are solely a matter of administrative convenience. The Births Deaths and Marriages record for me absolutely "knows" what my biological sex is, and my change of birth certificate has *not* made it possible for me to somehow "escape" the system in some fashion. Legally speaking it does not suddenly "magically" confer on me the right to be treated *exactly the same as a cisgender woman* either -- in New South Wales it means that I am now considered a "recognised transgender person" under the law and covered by anti-discrimination laws, but no more than that. So the fact that it now says "female" on the piece of paper does have a number of legal implications for me (and extremely important ones), but it does not make me the "same" as a cisgender woman legally.^[As a recent illustration of this in the Canadian context, consider the case of [Jessica Yaniv](https://www.thestar.com/vancouver/2019/10/22/transgender-woman-ordered-to-pay-over-her-rights-complaint-about-body-waxing.html) a transgender woman who attempted to force a business to provide her with a genital waxing service despite the fact that the business clearly only offers *vaginal* waxing and Yaniv had not had any form of genital surgery (as far as I'm aware). Even if the service if advertised as a service for women, and even if Yaniv is legally a woman, it does not follow that she can force a vendor to offer a specific genital waxing service that they quite clearly do not provide. This is an absurdity, as the court ruled, quite correctly in my opinion! Genital waxing -- besides sounding terribly painful -- is substantively a different service depending on what genitals you have. Abstract questions of whether "trans women are women" or whether women are "adult human females" are *utterly* beside the point, and the lettering on one's birth certificate is equally irrelevant in this context: non-discrimination protections aren't a licence to make absurd demands.] 

Irresepective of what it says on my birth certificate, the Australian Tax Office still has my tax file number, my Medicare records still correspond to the same person, my criminal record (or, thankfully, lack thereof) remains intact, my credit history is unchanged, and so on. This ought to be obvious to anyone with the slightest grasp of how the world works, but somewhat bizarrely I have seen people trying to incite moral panic by suggesting that predatory, criminal men could self-id as women and somehow escape police detection as a consequence. I hate to be the bearer of good news but please believe me... as a method of foiling the police this would be about as effective as foiling the NSA by using pig latin as an encryption cypher. The police know I'm transgender. Every government agency knows it. I might be able to conceal what I am from casual inspection by a taxi driver, but that's about as far as it goes, and I am no less subject to government surveillance than anyone else.^[Probably more than most, actually, when you think about the document trail that transitioning leaes behind...]

## Should self-identification be a sufficient criterion for legal recognition?

If we accept that transgender people do require some legal recognition (e.g., via reissued birth certificates), one what basis should this recognition be granted? One (strawman) possibility is that we allow a completely free "self identification" system, under which I am recognised as a woman *purely* because I say I am, and this self-identification cannot ever be questioned or challenged. I don't want such a system, and I don't think many transgender people do either.

The main reason I don't want a total lassaiz faire approach to legal documentation is that -- to put it crudely -- some men are assholes. If there are no penalties whatsoever for falsely declaring one's gender in a passport application or a driver's licence application, some men will take advantage of this. I've seen it happen. Sometimes the infraction is relatively minor -- as a recent example, a Canadian man took advantage of gender transition legislation to get [cheaper insurance premiums](https://www.cbc.ca/news/canada/calgary/change-gender-identification-insurance-alberta-1.4754416). This is of course a form of insurance fraud. Perhaps not the heinous of crimes, but I would not be at all surprised to find that there are some men who would try something like this for more predatory purposes. I have enough experience with abusive and predatory men that yes, I would (and do) accept some degree of intervention from the state in this context. A complete free for all on government documentation seems like a *really* bad idea in a world that contains assholes. Predators do exist, and as a practical matter some level of gatekeeping or oversight is a good idea.

What drives me to distraction is that my accepting the need for *some* gatekeeping does not obligate me to endorse the law as it currently stands in most Australian jurisdictions. I do not.

In fact, Australia makes an interesting case for discussing the possible legislative regimes, because all three of the "major" systems for legal recognition that I've seen discussed are in place in one jurisdiction or another. I don't know if there are any established names for these systems, but broadly speaking I think of them as the "surgical", "medical" and "declarative" models for transgender recognition. In increasing order of permissiveness, here they are...

- *The surgical model*. The "traditional" approach to transgender recognition is to require a complete surgical transition before any legal documentation can be issued. In everyday language: you have to get the sex change operation first, then you can update your drivers licence. This approach has fallen out of favour recently, but it still exists in several Australian states, including New South Wales. To my mind this model is pointlessly cruel: I cannot think of any legitimate public policy goal that is achieved by the NSW laws that is not *also* achieved by the more permissive South Australian laws. 

- *The medical model*. The law in South Australia adopts a medical perspective. Being transgender is still considered to be a medical condition, requiring a diagnosis of gender dysphoria from a medical practitioner (often a psychiatrist), along with evidence that this condition is being appropriately treated. South Australia was the first Australian state to adopt this law, in 2017, and so far it seems to be going smoothly. The sky has not fallen, Adelaide has not become a smoking pit in the ground, life goes on. The empirical evidence seems to be that there are no drawbacks to the SA process relative to the NSW one. 

  The main problem with the South Australian law is that it is still rather stigmatising to transgender people. Being trans is still implicitly viewed as a mental illness, which is a little depressing. Perhaps more substantively, it places spurious constraints on who can transition. For someone like myself -- white, affluent, middle-aged, cis-passing, etc -- it's not too hard to pay for the hormone treatment, laser treatment, psychiatrist visits and therapy sessions, and so on. It's humiliating, yes, and extraordinarily physically painful at times, but it's doable. That is not necessarily true for transgender people who lack my resources (and quite frankly it still sucks even for people who do). So if we can avoid systematic abuse within a less demeaning and less classist legal framework, that would be highly preferable. Which brings me to...

- *The declarative model*. The third kind of legislative regime I'm aware of is the one in place in Victoria and Tasmania. My understanding of the law there is that transgender status is not treated as a medical condition at all. You don't need a psychiatrist to assert that you are transgender, you can do it yourself by lodging a statutory declaration (a legal document that is akin to making a statement "under oath" as it were). This process requires a Justice of the Peace or police officer to sign off on the statutory declaration, as usual, but the key thing is that the transgender person isn't obligated to *prove* to the authority figure they are transgender "enough" in order to qualify. This is much kinder to transgender people, and on that basis it ought to be preferable unless there is reason to think that it would lead to other undesirable outcomes. 

  So the question now becomes... is there any such evidence? To my knowledge there isn't, and I can't really see why we should expect there to be. However, this assertion comes with a caveat: I am working from the assumption that the police would take infractions seriously. For example the man in Canada who attempted to "transition" in order to get lower insurance premiums genuinely should be subjected to a fairly severe financial penalty. It *is* an offence to make false statement in a statutory declaration, and it is most certainly an offence to use this false statement to defraud your insurance company. Moreover, it would be trivial to prove to the satisfaction of a reasonable person that this person had not been attempting to "live as a woman" (e.g., in this instance he openly admits this), he could -- and should -- be prosecuted for fraud. 
  
  To me, it is important that such penalties be enforced. To be honest I cannot say I care all that much about the rights of an insurance company, but I do care about the integrity of the gender recognition process. The safety of transgender people, cisgender women, and other people depend on the police and the courts being willing to enforce the law in this case, and not treat it as an amusing joke.  
  
  What all of this comes down to, from my perspective, is that the declarative model is perfectly sensible so long as the laws are properly enforced. In other words, my take on the declarative model is that it does not remove gatekeeping -- rather, it *shifts* the gatekeeping. It is removed at the time of application, but can be enforced, audited, verified and violations penalised after the fact. These rules are a form of gatekeeping, of course, but in my view a good one: it serves as a deterrent measure to prevent malicious actors taking advantage. To my mind this is a perfectly reasonable and defensible legal strategy that acknowledges the trade-offs involved. As I see it, there is no public policy need to force genuine trans folks to *prove* who we are at the time of applying for legal documentation, but only so long as there is also a properly enforced process by which violators can be subject to legal sanction. 

  To paraphrase *The Wire*: "fraud stays fraud", and should be punishable as such.

## Is self identification sufficient in sport?

The participation (or not) of transgender women in women's sport is something that gets people really worked up. Should trans women be allowed to play women's sport? Well, as with a lot of things in life, my own intuition is that it depends on context... 

In a lot of situations I'd argue that the answer is "sure why not?" If I were to sign up for an informal social women's table tennis competition, for example, I would expect that self-identification should be sufficient -- table tennis is a non-contact sport, and there's no financial stakes or prestige factors in play here. I'd likely have a substantial competitive advantage over most competitors, but that would be because I played competitive table tennis for about 10 years when I was younger! More importantly, even if I do have some kind of additional advantage conferred to me by virtue of my biology, it's not important enough for anyone to care what I do: we're talking about recreational sports. There are no stakes involved other than everyday politeness... in situations like this I would expect my self-identification to be perfectly sufficient because it's an everyday courtesy and nothing more.

However, while the vast majority of cases of trans women playing sport are probably more like my example above, those aren't really the situations we're talking about whenever we discuss "the sports question". Rather, we're focused on the uncommon cases, where there's something important at stake. From what I can tell, the discussion is (mostly but not exclusively) about professional sports, and the discussion turns on two quite different issues: there is a question of *safety*, and a question of *fairness.* I think the two need to be clearly distinguished.

I'll start by considering the question of safety, which is something of a red herring in my opinion. To see what I mean, consider the now-infamous case of whether [Hannah Mouncey](https://en.wikipedia.org/wiki/Hannah_Mouncey) should have been eligible to play Australian rules football in a women's competition? For the moment, let's ignore "fairness" as a criterion and ask if it is physically safe for the other athletes if she were allowed to enter the competition. Mouncey is physically much larger than most of the cisgender women playing in the competition (she is 6'2" according to Wikipedia, and is quite muscular), and Aussie rules is a very demanding contact sport. So does it pose a safety risk for her to play in the women's league? Well, yes, it might. So should she be banned *on this basis*?

Well, before jumping to conclusions, we should also consider the case of the 6'11" [Aaron Sandilands](https://en.wikipedia.org/wiki/Aaron_Sandilands). In terms of physical bulk, he dominated over other male AFL players to (at least!) the same extent that Mouncey would dominate over cisgender players in the women's league. So does it pose a safety risk for him to play in the men's league? Well, yes, it might. So should he be banned *on this basis*?

These two cases are structurally identical in pretty much every respect *except* for the fact that Mouncey is transgender. Unless we are willing to endorse the "magic transgender menace" hypothesis, namely that Mouncey's transgender status makes her a safety risk *in and of itself*, there's no safety reason to ban Mouncey and not Sandilands. In every other case besides trans women, when we are faced with a safety concern by virtue of the "argument from the very large player" we do not consider it appropriate to ban the very large players from the sport. If football becomes unsafe when a man of Sandilands' stature plays in the same competition as more modestly sized men, then what we actually do -- quite appropriately! -- is consider changing the rules so that it *becomes* a safe sport. 

I would argue that as regards the question of safety, we should treat the "argument from Hannah Mouncey" in much the same way we treat the "argument from Aaron Sandilands". Both are special cases of the "extremely large athlete" argument. Yes, it is true that trans women will tend to be larger than cis women, so the extremely large athlete argument is likely to involve trans women when it comes to women's sport, but it won't always play out like that... humans aren't *that* sexually dimorphous as a species: within-sex variation in size is too large and between-sex variation is too small for the "safety concern" about trans women to make much sense. 

So... yes, in all honesty I would have reservations about Hannah Mouncey playing AFL, but only in the sense that I would have similar reservations about Aaron Sandilands. That is to say, I have concerns about the safety of AFL as a sport in general. For me at least, this also generalises to boxing, rugby, MMA etc. If trans women pose a safety risk in your sport then your conclusion -- somewhat unpalatably in this instance because I actually kind of enjoy watching AFL -- has to be that your sport has a safety problem more generally. In short, framing "safety" as if it were an issue that is specific to transgender athletes is silly. Cisgender athletes deserve protection when playing sports, from each other as well as from us. 

Okay, so if the safety question is misguided, what of the question of fairness? To my mind this is a thornier question and in all honesty I don't pretend to know the answer. 

For what little it's worth I'll start by stating the obvious... this is not a context where self identification is a sufficient criterion. In the extreme case, suppose a transgender woman has not commenced medical transition *at all*. Biologically speaking, there's really no difference between her and a cisgender man. In this case, it's a matter of common sense that she ought not be participating in women's professional competitive sports, as a matter of fairness. But of course, that's not what we're really talking about when we consider the question of fairness. What we're really asking is something like this: under what conditions *would* it be fair to allow transgender women to participate in women's professional sport? Are the current rules fair?

As I say, the truth is that I don't know. There are some things I can say... for example, I can point to another common sense intuition, but this time from a trans woman's perspective. Call it the "pushup test" if you like.^[A side note. My understanding is that the scientific evidence on the effect of hormones on transgender athletes is modest and wouldn't treat anything I've read so far as dispositive. This is something where the first person knowledge comes in handy, but at most my experiences are anecdotal, and the studies that I've seen aren't much more than anecdotes] It is painfully obvious to me that I am physically weaker than I used to be, and that this change is especially pronounced for upper body strength. As an example: I can't do a single pushup any more, whereas prior to starting hormones I'd never been in a position where I couldn't at least manage a set of ten.^[Seriously, as I wrote this post I thought... okay, let's do this. Prove myself wrong. This time I will succeed damn it, I will do a single push up... yeah, nope. I almost did it, but not quite. One day I will succeed at this, because I am stubborn and bloody minded but apparently today is not that day.] Pushups were once easy, and now they are hard -- hormones certainly do have some effect on the physical abilities of trans women. But how large is that effect? I offer my silly pushup story *only* as an attempt to counter the "gut intuition" that some people have, namely that admitting trans women who have medically transitioned would be exactly as unfair as it would be if we allowed cisgender men to participate in womens's sports. I think that intuition is wrong, and the pushup anecdote is offered as evidence, but it doesn't have any interesting evidentiary value more generally -- it's just an anecdote.^[Additionally: because I care about accuracy, I hasten to note that the effect of hormones for me seems to be smaller for things like endurance. I run 5-7km fairly regularly, and while my times have declined quite substantually -- to the point that I'll probably never be competitive with my former self and I can't make it into my own top 50 any more no matter how hard I train -- the intuition I have is that the decline here is more modest.]

If we want to establish that it is fair to let trans women participate under some set of regulations, I'd want there to be some more substantial evidence that suggests that *as a category*, trans women don't have a substantial competitive advantage when those regulations are applied. We can't really reason from single persons here, because we need a rule that will work as an admissability criterion for a category. As for what that rule should be... I simply don't know. To me it seems like this is an empirical question not a moral one, and we won't know the answer for quite some time because the evidence isn't really "in" yet. It's easy to point to specific cases that seem odd (e.g., [Rachel McKinnon's](https://en.wikipedia.org/wiki/Rachel_McKinnon) remarkable success in cycling) but individual cases aren't dispositive either way. If my personal inability to do a pushup isn't a sufficient criterion (and it isn't), neither is McKinnon's cycling ability. For things like this we actually need better data than we have. 

Given all this, what seems to be happening on the ground is that individual sporting bodies are trying to do the right thing by setting rules for their sport on a "best guess" basis, using what limited evidence they have, and periodically refining those rules as new evidence comes in. Short of instituting an outright ban on transgender women in professional sport -- which does seem a little harsh to me -- I'm not sure what else they can do. It seems fairly reasonable to me?

TL;DR: the way I see it the safety issue is a distraction and the fairness question is hard.


## On public toilets (and changing rooms)

A lot of public debate centres on whether trans women should be allowed to use women's bathrooms, women's changing rooms, and so on. As with other topics, I think it's important to distinguish cases where there are relevant distinctions. Changing rooms and bathrooms are used for different purposes, and I find that I have quite different feelings about the two.

Speaking for myself I'm actually not comfortable with the idea of using women's changing rooms *or* men's changing rooms. This because I'm uncomfortable with being naked around people I don't know, or having people I don't know being naked around me. It upsets me that as a society we've designed changing spaces like this, and my own approach has been to opt out. I don't use changing rooms, I find some other space where I can change. That's what I did before transitioning too, to be honest. I suppose my "principle" in this instance is similar to how I feel about safety in the sporting context; the actual issue has nothing to do with trans people, and everything to do with the fact that the "changing room" environment is inherently unsafe to begin with. I recognise that other people feel differently, but that's certainly how I feel about it. It's all a bit Bartelby the Scrivener of me, I'll admit, but as regards changing rooms... I don't *have* to use them, I can participate in society perfectly fine without using them, and I would prefer not to. So I don't. No dramas there.

Bathrooms are a rather different matter. Using public toilets is a necessity for all of us, trans women included, and it is impractical to ban trans women from using women's bathrooms entirely. I'll try to illustrate why I think this by highlighting the shortcomings of the alternative "solutions" I sometimes see people suggesting.

Often in these discussions I see people arguing that the solution is to build dedicated third spaces for trans women to go to the toilet. Viewed as a concrete policy proposal rather than some handwavy abstraction this "solution" is frankly absurd. Setting aside the elephant in the room -- *that legislatively segregating trans women from the rest of the population will have a stigmatising effect on an already-vulnerable population* -- there's simply no budget for it. Who is going to pay for this? I am yet to see anything that looks like a concrete, workable financial proposal, and no politician is going to fund an extensive public works program solely because a few cisgender women don't like trans women. So while I personally am entirely on board with creating gender neutral toilets with private stalls (I think it's useful for lots of people, and for lots of reasons), the idea that we can retrofit all public spaces this way as a "here and now" solution to "the trans woman problem" is simply a nonstarter from a practical standpoint. 

Let's at least *try* to live in the real world, please?

Well, what about the men's room? If anything, this option is even more absurd. I speak from some personal experience here because I tried it. I was so very, very nervous about using the women's room -- after all, I really don't want to make anyone uncomfortable around me! -- and so I tried to avoid using women's bathrooms until I absolutely had to. As a consequence fo this I was using the men's bathroom quite late into my transition, well after I was passing as a woman, and some people really freaked out. Men would get annoyed at me for being in "their" toilet and tried to direct me to the women's room. Women would sometimes follow me into the men's room and would then blame me for their mistake.^[You know that thing where you just follow the crowd and don't bother to look at the signs yourself? Well that happened quite a bit and cisgender women were very displeased with me for leading them into the men's.] In other words, regardless of whether I am "really" a woman, I look enough like one that everyone expects me to use the women's bathroom. 

Contrary to what many people say on the internet, it's very clear to me from my everyday life that everyone expects me to use the women's bathroom. If I try to do anything *other* than use the women's room it is perceived as a massive breach of everyday social norms. So when there is no accessible unisex toilet around, as there very often is not^[To counter an obvious question, well, why can't I use the disabled toilets like disabled people do? Why can't trans women do the same thing instead of intruding on women's spaces? Firstly, contrary to what is often said about is I'm really not keen on intruding in other people's spaces, and an accessible toilet actually *is* someone else's space. There's a serious shortage of good accessible toilets, and it's pretty gross to take those resources from disabled folks who actually need them just because some cisgender people find trans women icky. Secondly, as I discovered during the phase where I was too scared to use the women's room or the men's room... there's a bit of a scarcity problem there too. Maybe this is naive of me, but I was kind of shocked to discover just how bad the situation is for accessible toilets. A lot of places don't have any usable facilities, others "appear" to have them but when you get there you discover that the toilet is locked, and there is no-one you can contact to get them opened etc. It's infuriating. I can't even imagine how annoyed wheelchair users must feel about this. In any case, I'll stop talking on this topic now because I feel like this is actually something where it makes more sense to listen to people with disabilities rather than me: I only mention this because I don't think "use the disabled toilets" is actually a practical solution either.] my choices are to use the women's bathroom or not leave the house at all. So oddly enough, because I need to leave the house to do my job and be a functioning, taxpaying member of society I use the women's bathroom, and nobody seems to mind. 

What I'm trying to get at here is that people *need* toilets in a way that they don't need other amenities, and as a consequence a ban on trans women from using women's toilets becomes a de facto ban -- or at least, a very severe constraint -- on trans women participating in public life. Is there any public policy basis for enforcing such a ban? I'm yet to see a single argument to that effect that even comes close to offering such a justfication. Banning trans women won't protect cis women from sexual predators, not as far as I can see, but it certainly puts trans women in a severe bind.

## Domestic violence shelters

Another big issue I see arising in this debate is access to domestic violence shelters -- should trans women be allowed in these spaces? My perspective on this is fairly heavily shaped by my experiences with being raped, and with being an "unusual" rape survivor who doesn't fit the stereotypes. This is something I'm pretty angry about and I'll ask the reader to forgive my bluntness -- this is not a subject I can discuss without my own anger coming to the surface.

Given my history, it's probably no surprise that I think resources for the protection of rape survivors and domestic violence victims should *NOT* be allocated on the basis of gender *or* sex. They should be allocated to people on the basis of whether one has experienced rape or domestic violence. What this means is that yes, a male survivor of rape absolutely deserves a place in a rape shelter regardless of his genitals; and a female rapist has no such right, regardless of hers. Rape and domestic violence occurs in the LGBTIQ commmunity too (and is rarely reported because the police are fucking useless) and an ethical society does *NOT* allow rapists into a survivors shelter regardless of what fucking genitals they have. End of fucking story.^[As I say, I do recognise I'm being angry and emotional on this point, and I'm genuinely sorry for that. But at the same time, I'm a rape victim too and I think I'm allowed to be just as angry about rapists as any other survivor. So honestly, if your feeling is that it's only cis women who have been raped by men that get the right to be angry about sexual violence then you're no ally to rape victims and you can just fuck right off.] 

In practice, due to the fact that abusers tend to be men and victims tend to be women, rape shelters and domestic violence shelters will be filled mostly with women and children, but not entirely. And of course there is an important practical question as to how a specific shelter arranges a policy that allows access for victims and denies it to abusers. I don't think this is an easy problem to solve (and feel that individual shelters are probably best placed to set their own policies) but I do want to suggest that neither "genitalia" nor "chromosomes" make a sound basis for that policy; nor for that matter, does "gender". In this context our policy goal is to provide support and protection for *victims of abuse*, not for a sex category or a gender category.

*No* rape survivor gets left out in the cold: that's how this is supposed to work.

## Dating

There is a lot said about dating and disclosure. When is a trans woman expected to "disclose" her status as a trans woman, is there transphobia in the world of relationships, etc etc. Yet again, I think it is important to separate different cases and consider them on their own terms rather than look for some overarching "rules for life".^[Philosophically speaking, I am very much a fan of the oft-maligned position of [casuistry](https://en.wikipedia.org/wiki/Casuistry). I tend to have a very low opinion of "general principles": I do not find *either* the trans-inclusive slogan "trans women are women" or the trans-exclusionary one "woman is an adult human female" to be useful guidelines for practical decision-making. I think in most cases policy matters need to be resolved at a more local level, considering the specifics of the situation. Analogies between one case and another can be helpful, but are not dispositive. On matters of morality I tend to be ruthlessly practical and have almost no time for people wanting to "reason from afar" or from high-minded principles about "consequentialism" and the like. I think this kind of reasoning is worse than useless -- it solves no real world problems, and if anything it tends to create new problems because people now become obsessed with "the principle of the thing" instead of trying to *fix* the substantive problem at hand.] 

Suppose for example we're talking about a question like this one: "should a trans woman who has had gender reassignment surgery and passes for a cis woman be *obligated* to disclose this fact to a sexual partner?" I'm going to say she has no such obligation, especially to men. Personally I am not all that keen on the prospect of being [strangled, dismembered and cooked in my own oven](https://www.gaystarnews.com/article/russian-doctor-murdered-dismembered-and-cooked-a-trans-woman/) and I don't think it's unreasonable for a trans woman dating a man to consider her own safety as the paramount concern. Sometimes that might make disclosure the best strategy, sometimes it doesn't. But in this context the decision to disclose is solely at the discretion of the trans woman. Less dramatically, I think that the issues around disclosure, particularly as they pertain to men, are nicely captured by [this article](http://www.newnownext.com/we-had-sex-but-i-never-told-him-im-trans/08/2017/) by Jen Richards. In general, I think one is no more obligated to disclose one's transgender status than any other personal detail -- just because you're fucking me doesn't give you the right to my life story.

There are other kinds of question to consider though. For example, there's the question of whether a specific person is bigoted or transphobic if they do not want to have sex with a transgender person. Personally I think the answer is "no, of course not" and I don't understand how this is even a question. 

If you don't want to have sex with me (or anyone else) you have the absolute right not to do so, on more or less any basis you like. Sure, I'm not obligated to disclose my life story or my sexual history to you, but that's more akin to me not being obligated to show you my bank records or my medical records. If you don't want to date me because of my appearance, my genitals, my skin colour, or even my transgender status (since in my case I'm quite open about it) etc, etc... go right ahead. That's your absolute right. 

In a way, I'm sort of puzzled by the question, and I wonder whether what's happening in these cases is that people are confusing abstractions with specifics. In a number of areas writers have discussed the *abstract* question about prejudice as it relates to sex and relationships. To what extent, for example, do social norms and stereotypes negatively affect the dating prospects of fat people? People of colour? Etc. "Political critiques of desire" at this abstract level are quite common, and are considered very reasonable, but it is commonly understood that such abstract critiques do *not* have implications for specific cases. If you don't want to date me because of my weight (let's say), that is absolutely your decision. When authors write about "fatphobia", for example, they are describing a population level dynamic, and are not making claims about any specific person's dating choices. The same is true as regards the "cotton ceiling" discussions that surround trans women's dating prospects. Population level discussions about biases are reasonable and sensible; using those discussions to justify an individual level attribution of bias are not. Surely this is obvious?


## Prisons

The last big issue that comes to mind is how transgender women should be accommodated within prisons, if we are found guilty of a crime. Do you place a trans woman in a men's prison or a women's prison? As is becoming tediously predictable, my answer to the question is to say it depends on the particulars. 

As a *default*, I'd say that if a transgender woman has already met the criteria to obtain legal documentation within, then she should be housed in a women's prison. When I think of the level of terror I have around sexual assault if I were to be placed in a prison with men I am aghast at the thought that people would ignore my documentation, my physical transiton, etc and decide to assign me to a prison based on my chromosomes. Given the obvious lack of safety in the prison system, this is more or less guaranteeing that I will be raped. 

Rape is not an accepted legal punishment for a crime, so until you can show me that you've developed a prison system that eliminates prison rape, my concerns about sexual violence should be taken seriously, no less than those a cisgender woman might have. As a default regarding trans women, I feel quite strongly about that. 

Where this becomes murkier is... what of transgender men? How does a prison system keep them safe? As is often the case, disussions about the rights of transgender people are focused on restricting (or permitting) trans women access to legal protection. I think that in most cases the discussion plays out that way because so many cisgender people perceive us (trans women) to be a threat. Obviously I think those concerns are misplaced, and but one negative consequence of this relentless focus on the ostensible threat of trans women is that the concerns of trans men and nonbinary people disappear from view.^[This seems as good a moment as any to mention (again!) that the reason I'm focusing on trans women specifically is that I *am* a trans woman -- it's a topic I know something about. I don't comment much on the concerns of trans men or nonbinary people because I feel quite out of my depth, and don't wish to step out of my lane. However, because there is a group of transgender people who adopt a "transmedicalist" position that would throw nonbinary people under the bus... yeah, I'm not one of those people either. Transgender rights is a much bigger topic than the concerns of trans women!]  I'm quite uncomfortable with this erasure in general. Up to this point in my post the issue hasn't come up (e.g., I see no problems with allowing trans men access to domestic violence shelters on the same basis as everyone else -- if they have experienced domestic violence then they deserve a place) but this is one area that I feel deserves a lot more consideration than I've provided here.

That said, I'm not going to offer any opinions in this respect due to my own lack of experience... I don't feel that *I* am the right person to speak to this. As with abortion and reproductive rights and other such issues that don't affect me directly, it isn't my place to hold strong opinions, and I'd rather listen to the people who are affected.

Returning to the question of transgender women in prison, there's a second type of situation I want to mention, namely "what rules should apply for someone who wants to transition from male to female *within* the prison system?" and in this context I think of two illustrative examples: Chelsea Manning and Karen White. It is pretty obvious to me and to most people that Chelsea Manning is genuinely a transgender woman, and when she was incarcerated she had not transitioned previously only due to a lack of opportunity. There was (and is) no basis to think she would pose a threat to other women, no reason to think that her request to transition was for any malicious purpose, so I see no reason why she ought to have been prevented from transitioning, and housing her in a women's prison seems appropriate. There's no threat to cisgender women in this scenario, and so accomodating Chelsea Manning as a woman is not problematic.^[Mind you, there's the rather different question about whether the prison system itself is defensible... I offer no opinion on that topic, as I think it's a bit above my pay grade.]

[Karen White](https://www.theguardian.com/uk-news/2018/oct/11/transgender-prisoner-who-sexually-assaulted-inmates-jailed-for-life), on the other hand, represents a very different kind of case, and one that deserves a lot more scrutiny and oversight. I'll admit I don't know a lot about the particulars but my understanding is that she^[For the moment I'm stipulating she was genuine in the desire to transition, which I'll admit does seem a little doubtful, but I'll let it slide because I have no evidence one way or the other.] is a convicted rapist. *If* we as a society are going to allow convicted rapists the right to transition within the prison system (and it's by no means a given that we should), then no, we do not give them any access to the same population of people they raped. That is not even close to being acceptable or ethical. As a depressingly personal example, the fact that I have legally transitioned from male to female does not mean that there is some moral or legal basis by which my (female) rapist suddenly deserves access to my person. That is fucking absurd.^[Again, sorry for the language, but yes I am angry. I have little patience for people who want to talk about the rights of rapists. Yes, they deserve the bare minimum of civil rights that the rest of us get -- no death penalty, no rape as punishment, etc -- but that's about as far as my willingness to stomach concern trolling in defence of rapists extends. Fuck that shit, seriously.] 

As much as any other rape victim does, I expect a much higher level of scrutiny to apply in this situation -- this actually *is* a scenario where I think someone has to prove they really are trans before being allowed to transition, and even if permission is granted they don't get access to the general population. That's just a massive NOPE from me. 

## Epilogue: What of metaphysics?

Throughout this post I've tried to focus on practical issues surrounding transgender rights, and not bothered much with abstract philosophical questions. This might seem surprising, given the level of vitriol about transgender rights in philosophical circles. What is the metaphysical status of a trans woman? Are we "really" women? What is the ontological status of gender identity? These and similar questions seem to have become a preoccupation for quite a few philosophers, to the point where it has become an extraordinarily emotive debate among my academic colleagues. It is puzzling to me.

The thing with these kinds of questions, as I see it, is that they don't have an answer because they are not well-posed. On one definition of "woman" I am a real woman. On another definition I am not. In everyday language we seamlessly switch between different definitions as needed by the context. Even in substantively important scenarios like legal documentation, professional sports and prisons, we switch between different conceptual frameworks as the circumstances demand, and *at no point* do abstract questions about metaphysics actually make a difference to our reasoning. Metaphysics plays no causal role in our thinking and practical decision making about transgender people: it is entirely epiphenominal. In this post, for instance, I've sketched out the core of my opinions about transgender rights on a purely practical commonsense basis, and not once did I feel any need or desire to make an appeal to metaphysics. Such matters may be of some academic interest to philosophers, but I don't think they're useful in real life.

<br><br>
